(function (root) {
  var SF = root.SF, F = SF.F, n = SF.n, extra = SF.extra;
  SF.add({
    id: 'bol-nl', currency: 'EUR', flag: '🇳🇱', platform: 'bol', region: 'NL/BE', countries: ['NL'],
    slug: { en: 'bol-fee-calculator', de: 'bol-gebuehrenrechner', fr: 'bol-calculateur-commission', it: 'bol-calcolo-commissioni', es: 'bol-calculadora-comisiones', nl: 'bol-commissie-berekenen', ja: 'bol-fee-calculator', ko: 'bol-fee-calculator' },
    fields: [F.price(29.95), F.shipping(0), F.cost(12), F.shipCost(4.5),
      F.cat(['12.4', '12.4+2.48', '12.4+0+1', '4.1', '5', '6', '10.8', '13', '14.1', '15', '20.7'], '12.4'), F.commission(12.4),
      { k: 'div', l: 'div', t: 'sel', d: '1', o: [{ l: 'incl', v: '1' }, { l: 'ex21', v: '1.21' }, { l: 'ex9', v: '1.09' }] },
      F.vat(21), F.other(), F.target()],
    fees: function (v) {
      var p = n(v.price);
      var fixed = p <= 10 ? 0.20 : p <= 20 ? 0.40 : (extra(v, 1) || 0.85);
      var sur = extra(v, 2);
      var com = (p / n(v.div || 1)) * n(v.commission) / 100;
      return [{ k: 'fixed', a: fixed }, { k: 'surcharge', a: sur }, { k: 'commission', a: com }, { k: 'vatOnFees', a: (fixed + sur + com) * n(v.vat) / 100 }, { k: 'otherCost', a: p * n(v.other) / 100 }];
    },
    sources: [{ n: 'Boloo: commissies bol.com 2026', u: 'https://www.boloo.co/blog/commissies-bol-com' }, { n: 'Product Tickler: bol bemiddelingsbijdrage berekenen', u: 'https://producttickler.nl/bol-fee-calculator/' }, { n: 'bol Partnerplatform – commissie', u: 'https://partnerplatform.bol.com/' }],
    s: {
      en: { title: 'bol.com Fee Calculator 2026 – Commission, Payout, Profit', desc: 'Free bol.com commission calculator: fixed fee per price band plus 4.1–20.7 % by category, VAT, payout, net profit and break-even price. 2026 rates.', h1: 'bol Fee Calculator (2026)', intro: 'The bol commission (Netherlands/Belgium) has two parts: a fixed amount per item sold (€0.20 to €0.85, higher for some electronics) plus a percentage of the selling price by category (12.4 % standard, from 4.1 % to 20.7 %). Both are ex VAT. This calculator adds it all up and shows your payout, net profit and break-even price.',
        cats: ['Standard (most categories) – 12.4 %', 'Electronics (fixed fee €2.48 above €20) – 12.4 %', 'Books, games, music, films (+ €1.00 media surcharge) – 12.4 %', 'Power tools – 4.1 %', 'Kitchen appliances – 5.0 %', 'Pet food – 6.0 %', 'Camping – 10.8 %', 'Fashion & sport (above €50) – 13.0 %', 'Bedding – 14.1 %', 'Beauty & care – 15.0 %', 'Jewellery – 20.7 %'],
        f: { div: 'Percentage calculated on' }, o: { incl: 'Price incl. VAT', ex21: 'Price ex 21 % VAT', ex9: 'Price ex 9 % VAT' }, fee: { fixed: 'Fixed fee per item', surcharge: 'Media surcharge', commission: 'Variable commission' },
        notes: ['Fixed fee per item: €0.20 (up to €10), €0.40 (€10–20), €0.85 (above €20); some electronics above €20: €2.48. Media (books, games, music, films): + €1.00.', 'Percentage by category, 12.4 % standard. All amounts ex VAT; bol charges 21 % VAT on the commission (recoverable if you are VAT registered).', 'No monthly fee; you only pay when you sell.', 'Enter your own shipping or LVB (fulfilment by bol) costs under “your shipping cost”.'],
        faq: [{ q: 'How high is the bol commission?', a: 'A fixed amount per item sold (€0.20 up to €10, €0.40 between €10 and €20, €0.85 above €20; some electronics €2.48) plus a percentage by category: 12.4 % standard, from 4.1 % (power tools) to 20.7 % (jewellery). All ex VAT.' }, { q: 'Does bol charge a monthly fee?', a: 'No. Selling via bol has no subscription; you only pay commission on items sold.' }, { q: 'Is VAT charged on the commission?', a: 'Yes, bol adds 21 % VAT to the commission. If you are VAT registered you deduct it, so it is not a cost. Otherwise choose the “not VAT registered” option.' }, { q: 'What is the media surcharge?', a: 'For books, games, music and films bol charges an extra €1.00 per item on top of the fixed fee and the percentage.' }] },
      de: { title: 'bol.com Gebührenrechner 2026 – Provision und Gewinn', desc: 'Kostenloser bol.com Provisionsrechner: Festbetrag je Preisstufe plus 4,1–20,7 % je Kategorie, MwSt., Auszahlung und Break-even-Preis.', h1: 'bol Gebührenrechner (2026)', intro: 'Die bol-Provision (Niederlande/Belgien) besteht aus zwei Teilen: einem Festbetrag pro verkauftem Artikel (0,20 € bis 0,85 €, höher für manche Elektronik) plus einem Prozentsatz des Verkaufspreises je Kategorie (Standard 12,4 %, von 4,1 % bis 20,7 %). Beides netto. Der Rechner addiert alles und zeigt Auszahlung, Nettogewinn und Break-even-Preis.',
        cats: ['Standard (meiste Kategorien) – 12,4 %', 'Elektronik (Festbetrag 2,48 € über 20 €) – 12,4 %', 'Bücher, Games, Musik, Filme (+ 1,00 € Medienzuschlag) – 12,4 %', 'Elektrowerkzeug – 4,1 %', 'Küchengeräte – 5,0 %', 'Tierfutter – 6,0 %', 'Camping – 10,8 %', 'Mode & Sport (über 50 €) – 13,0 %', 'Bettwaren – 14,1 %', 'Beauty & Pflege – 15,0 %', 'Schmuck – 20,7 %'],
        f: { div: 'Prozentsatz berechnet auf' }, o: { incl: 'Preis inkl. MwSt.', ex21: 'Preis ohne 21 % MwSt.', ex9: 'Preis ohne 9 % MwSt.' }, fee: { fixed: 'Festbetrag pro Artikel', surcharge: 'Medienzuschlag', commission: 'Variable Provision' },
        notes: ['Festbetrag pro Artikel: 0,20 € (bis 10 €), 0,40 € (10–20 €), 0,85 € (über 20 €); manche Elektronik über 20 €: 2,48 €. Medien (Bücher, Games, Musik, Filme): + 1,00 €.', 'Prozentsatz je Kategorie, Standard 12,4 %. Alle Beträge netto; bol berechnet 21 % MwSt. auf die Provision (erstattungsfähig bei Vorsteuerabzug).', 'Keine Monatsgebühr; du zahlst nur bei Verkauf.', 'Eigene Versandkosten oder LVB-Gebühren (Logistik über bol) unter „Deine Versandkosten“ eintragen.'],
        faq: [{ q: 'Wie hoch ist die bol-Provision?', a: 'Ein Festbetrag pro verkauftem Artikel (0,20 € bis 10 €, 0,40 € zwischen 10 und 20 €, 0,85 € über 20 €; manche Elektronik 2,48 €) plus ein Prozentsatz je Kategorie: Standard 12,4 %, von 4,1 % (Elektrowerkzeug) bis 20,7 % (Schmuck). Alles netto.' }, { q: 'Gibt es eine Monatsgebühr bei bol?', a: 'Nein. Verkaufen über bol hat kein Abo; du zahlst nur Provision auf verkaufte Artikel.' }, { q: 'Kommt MwSt. auf die Provision?', a: 'Ja, bol berechnet 21 % MwSt. auf die Provision. Vorsteuerabzugsberechtigte Händler holen sie zurück, dann sind es keine Kosten. Sonst die Option „nicht vorsteuerabzugsberechtigt“ wählen.' }, { q: 'Was ist der Medienzuschlag?', a: 'Für Bücher, Games, Musik und Filme berechnet bol 1,00 € extra pro Artikel zusätzlich zu Festbetrag und Prozentsatz.' }] },
      fr: { title: 'Calculateur de commission bol.com 2026 – frais et marge', desc: 'Calculateur gratuit des frais bol.com : montant fixe par tranche de prix plus 4,1–20,7 % selon catégorie, TVA, montant reversé et bénéfice.', h1: 'Calculateur de commission bol (2026)', intro: 'La commission bol (Pays-Bas/Belgique) comporte deux parties : un montant fixe par article vendu (0,20 € à 0,85 €, plus élevé pour certains produits électroniques) plus un pourcentage du prix de vente selon la catégorie (12,4 % standard, de 4,1 % à 20,7 %). Les deux sont hors TVA. Le calculateur additionne tout et affiche montant reversé, bénéfice net et prix d’équilibre.',
        cats: ['Standard (la plupart des catégories) – 12,4 %', 'Électronique (montant fixe 2,48 € au-dessus de 20 €) – 12,4 %', 'Livres, jeux, musique, films (+ 1,00 € supplément médias) – 12,4 %', 'Outillage électrique – 4,1 %', 'Appareils de cuisine – 5,0 %', 'Alimentation animale – 6,0 %', 'Camping – 10,8 %', 'Mode & sport (au-dessus de 50 €) – 13,0 %', 'Literie – 14,1 %', 'Beauté & soins – 15,0 %', 'Bijoux – 20,7 %'],
        f: { div: 'Pourcentage calculé sur' }, o: { incl: 'Prix TTC', ex21: 'Prix hors TVA 21 %', ex9: 'Prix hors TVA 9 %' }, fee: { fixed: 'Montant fixe par article', surcharge: 'Supplément médias', commission: 'Commission variable' },
        notes: ['Montant fixe par article : 0,20 € (jusqu’à 10 €), 0,40 € (10–20 €), 0,85 € (au-dessus de 20 €) ; certains produits électroniques au-dessus de 20 € : 2,48 €. Médias (livres, jeux, musique, films) : + 1,00 €.', 'Pourcentage selon la catégorie, 12,4 % standard. Tous les montants sont HT ; bol facture 21 % de TVA sur la commission (récupérable si vous êtes assujetti).', 'Pas de frais mensuels ; vous ne payez qu’en cas de vente.', 'Saisissez vos frais d’expédition ou LVB (logistique via bol) dans « Vos frais d’expédition ».'],
        faq: [{ q: 'Quel est le montant de la commission bol ?', a: 'Un montant fixe par article vendu (0,20 € jusqu’à 10 €, 0,40 € entre 10 et 20 €, 0,85 € au-dessus de 20 € ; certains produits électroniques 2,48 €) plus un pourcentage selon la catégorie : 12,4 % standard, de 4,1 % (outillage électrique) à 20,7 % (bijoux). Le tout HT.' }, { q: 'bol facture-t-il un abonnement mensuel ?', a: 'Non. Vendre via bol ne nécessite aucun abonnement ; vous ne payez que la commission sur les articles vendus.' }, { q: 'Y a-t-il de la TVA sur la commission ?', a: 'Oui, bol ajoute 21 % de TVA sur la commission. Si vous êtes assujetti, vous la récupérez et ce n’est pas un coût. Sinon choisissez l’option « non assujetti ».' }, { q: 'Qu’est-ce que le supplément médias ?', a: 'Pour les livres, jeux, musique et films, bol facture 1,00 € de plus par article en plus du montant fixe et du pourcentage.' }] },
      it: { title: 'Calcolatore commissioni bol.com 2026 – costi e profitto', desc: 'Calcolatore gratuito delle commissioni bol.com: importo fisso per fascia di prezzo più 4,1–20,7 % per categoria, IVA, accredito e profitto.', h1: 'Calcolatore commissioni bol (2026)', intro: 'La commissione bol (Paesi Bassi/Belgio) ha due componenti: un importo fisso per articolo venduto (da €0,20 a €0,85, più alto per alcuni prodotti elettronici) più una percentuale del prezzo di vendita per categoria (12,4 % standard, dal 4,1 % al 20,7 %). Entrambi al netto di IVA. Il calcolatore somma tutto e mostra accredito, profitto netto e prezzo di pareggio.',
        cats: ['Standard (maggior parte delle categorie) – 12,4 %', 'Elettronica (importo fisso €2,48 sopra €20) – 12,4 %', 'Libri, giochi, musica, film (+ €1,00 supplemento media) – 12,4 %', 'Elettroutensili – 4,1 %', 'Elettrodomestici da cucina – 5,0 %', 'Cibo per animali – 6,0 %', 'Campeggio – 10,8 %', 'Moda & sport (sopra €50) – 13,0 %', 'Biancheria da letto – 14,1 %', 'Beauty & cura – 15,0 %', 'Gioielli – 20,7 %'],
        f: { div: 'Percentuale calcolata su' }, o: { incl: 'Prezzo IVA inclusa', ex21: 'Prezzo senza IVA 21 %', ex9: 'Prezzo senza IVA 9 %' }, fee: { fixed: 'Importo fisso per articolo', surcharge: 'Supplemento media', commission: 'Commissione variabile' },
        notes: ['Importo fisso per articolo: €0,20 (fino a €10), €0,40 (€10–20), €0,85 (sopra €20); alcuni prodotti elettronici sopra €20: €2,48. Media (libri, giochi, musica, film): + €1,00.', 'Percentuale per categoria, 12,4 % standard. Tutti gli importi al netto di IVA; bol applica il 21 % di IVA sulla commissione (detraibile se hai partita IVA).', 'Nessun canone mensile; paghi solo quando vendi.', 'Inserisci i tuoi costi di spedizione o LVB (logistica tramite bol) in “tuo costo di spedizione”.'],
        faq: [{ q: 'Quanto è la commissione bol?', a: 'Un importo fisso per articolo venduto (€0,20 fino a €10, €0,40 tra €10 e €20, €0,85 sopra €20; alcuni prodotti elettronici €2,48) più una percentuale per categoria: 12,4 % standard, dal 4,1 % (elettroutensili) al 20,7 % (gioielli). Tutto al netto di IVA.' }, { q: 'bol applica un canone mensile?', a: 'No. Vendere tramite bol non richiede abbonamento; paghi solo la commissione sugli articoli venduti.' }, { q: 'C’è IVA sulla commissione?', a: 'Sì, bol aggiunge il 21 % di IVA sulla commissione. Se hai partita IVA la detrai e non è un costo. Altrimenti scegli l’opzione “non detraibile”.' }, { q: 'Cos’è il supplemento media?', a: 'Per libri, giochi, musica e film bol addebita €1,00 in più per articolo oltre all’importo fisso e alla percentuale.' }] },
      es: { title: 'Calculadora de comisiones bol.com 2026 – tarifas y margen', desc: 'Calculadora gratuita de comisiones de bol.com: importe fijo por tramo de precio más 4,1–20,7 % por categoría, IVA, importe recibido y beneficio.', h1: 'Calculadora de comisiones bol (2026)', intro: 'La comisión de bol (Países Bajos/Bélgica) tiene dos partes: un importe fijo por artículo vendido (de 0,20 € a 0,85 €, mayor para cierta electrónica) más un porcentaje del precio de venta según categoría (12,4 % estándar, del 4,1 % al 20,7 %). Ambos sin IVA. La calculadora lo suma todo y muestra importe recibido, beneficio neto y precio de equilibrio.',
        cats: ['Estándar (mayoría de categorías) – 12,4 %', 'Electrónica (importe fijo 2,48 € por encima de 20 €) – 12,4 %', 'Libros, juegos, música, películas (+ 1,00 € suplemento medios) – 12,4 %', 'Herramientas eléctricas – 4,1 %', 'Electrodomésticos de cocina – 5,0 %', 'Comida para mascotas – 6,0 %', 'Camping – 10,8 %', 'Moda y deporte (por encima de 50 €) – 13,0 %', 'Ropa de cama – 14,1 %', 'Belleza y cuidado – 15,0 %', 'Joyería – 20,7 %'],
        f: { div: 'Porcentaje calculado sobre' }, o: { incl: 'Precio con IVA', ex21: 'Precio sin IVA 21 %', ex9: 'Precio sin IVA 9 %' }, fee: { fixed: 'Importe fijo por artículo', surcharge: 'Suplemento medios', commission: 'Comisión variable' },
        notes: ['Importe fijo por artículo: 0,20 € (hasta 10 €), 0,40 € (10–20 €), 0,85 € (más de 20 €); cierta electrónica por encima de 20 €: 2,48 €. Medios (libros, juegos, música, películas): + 1,00 €.', 'Porcentaje por categoría, 12,4 % estándar. Todos los importes sin IVA; bol cobra un 21 % de IVA sobre la comisión (recuperable si eres sujeto pasivo).', 'Sin cuota mensual; solo pagas cuando vendes.', 'Introduce tus propios costes de envío o de LVB (logística vía bol) en “tu coste de envío”.'],
        faq: [{ q: '¿Cuánto es la comisión de bol?', a: 'Un importe fijo por artículo vendido (0,20 € hasta 10 €, 0,40 € entre 10 y 20 €, 0,85 € por encima de 20 €; cierta electrónica 2,48 €) más un porcentaje por categoría: 12,4 % estándar, del 4,1 % (herramientas eléctricas) al 20,7 % (joyería). Todo sin IVA.' }, { q: '¿bol cobra una cuota mensual?', a: 'No. Vender a través de bol no requiere suscripción; solo pagas comisión por los artículos vendidos.' }, { q: '¿Se cobra IVA sobre la comisión?', a: 'Sí, bol añade un 21 % de IVA a la comisión. Si eres sujeto pasivo lo deduces y no es un coste. Si no, elige la opción “sin IVA deducible”.' }, { q: '¿Qué es el suplemento de medios?', a: 'Para libros, juegos, música y películas bol cobra 1,00 € más por artículo además del importe fijo y del porcentaje.' }] },
      nl: { title: 'bol.com commissie berekenen 2026 – kosten en winst', desc: 'Gratis bol.com commissiecalculator: vast bedrag per prijsklasse plus 4,1–20,7 % per categorie, btw, uitbetaling, nettowinst en break-evenprijs.', h1: 'bol commissie berekenen (2026)', intro: 'De commissie van bol bestaat uit twee delen: een vast bedrag per verkocht artikel (€ 0,20 tot € 0,85, hoger voor bepaalde elektronica) plus een percentage van de verkoopprijs per categorie (standaard 12,4 %, van 4,1 % tot 20,7 %). Beide zijn exclusief btw. Deze calculator telt alles op en toont je uitbetaling, nettowinst en break-evenprijs.',
        cats: ['Standaard (meeste categorieën) – 12,4 %', 'Elektronica (vast bedrag € 2,48 boven € 20) – 12,4 %', 'Boeken, games, muziek, films (+ € 1,00 mediatoeslag) – 12,4 %', 'Elektrisch gereedschap – 4,1 %', 'Keukenapparatuur – 5,0 %', 'Dierenvoeding – 6,0 %', 'Kampeerartikelen – 10,8 %', 'Mode & sport (boven € 50) – 13,0 %', 'Beddengoed – 14,1 %', 'Beauty & verzorging – 15,0 %', 'Sieraden – 20,7 %'],
        f: { div: 'Percentage berekenen over' }, o: { incl: 'Verkoopprijs incl. btw', ex21: 'Verkoopprijs excl. 21 % btw', ex9: 'Verkoopprijs excl. 9 % btw' }, fee: { fixed: 'Vast bedrag per artikel', surcharge: 'Mediatoeslag', commission: 'Variabele commissie' },
        notes: ['Vast bedrag per artikel: € 0,20 (t/m € 10), € 0,40 (€ 10–20), € 0,85 (boven € 20); bepaalde elektronica boven € 20: € 2,48. Media (boeken, games, muziek, films): + € 1,00.', 'Percentage per categorie, standaard 12,4 %. Alle bedragen excl. btw; bol brengt 21 % btw over de commissie in rekening (aftrekbaar als je btw-plichtig bent).', 'Geen maandelijkse kosten; je betaalt alleen bij verkoop.', 'Verzendkosten (eigen verzending of LVB) vul je in bij „jouw verzendkosten”.'],
        faq: [{ q: 'Hoe hoog is de commissie van bol?', a: 'Een vast bedrag per verkocht artikel (€ 0,20 t/m € 10, € 0,40 tussen € 10 en € 20, € 0,85 boven € 20; bepaalde elektronica € 2,48) plus een percentage per categorie: standaard 12,4 %, van 4,1 % (elektrisch gereedschap) tot 20,7 % (sieraden). Alles exclusief btw.' }, { q: 'Betaal ik maandelijkse kosten aan bol?', a: 'Nee. Verkopen via bol kent geen abonnement; je betaalt alleen commissie op verkochte artikelen.' }, { q: 'Komt er btw over de commissie?', a: 'Ja, bol rekent 21 % btw over de commissie. Ben je btw-plichtig, dan trek je die af en is het geen kostenpost. Val je onder de KOR, kies dan die optie in de calculator.' }, { q: 'Wat is de mediatoeslag?', a: 'Voor boeken, games, muziek en films rekent bol € 1,00 extra per artikel bovenop het vaste bedrag en het percentage.' }] },
      ja: { title: 'bol 手数料計算ツール 2026｜手数料・入金額・商品ごとの利益', desc: 'オランダ・ベルギーのbol.comの手数料を無料計算：価格帯別の固定額＋カテゴリ別4.1〜20.7%、手数料の付加価値税、入金額、純利益、利益率、損益分岐価格。', h1: 'bol 手数料計算ツール（2026年版）', intro: 'bol（オランダ／ベルギー）の手数料は2段構えです：販売1点ごとの固定額（€0.20〜€0.85、一部の電子機器はより高額）に加え、カテゴリ別の販売価格に対する割合（標準12.4%、4.1〜20.7%）。いずれも税別。すべてを合算し、入金額・純利益・損益分岐価格を表示します。',
        cats: ['標準（ほとんどのカテゴリ）– 12.4%', '電子機器（€20超は固定額€2.48）– 12.4%', '本・ゲーム・音楽・映画（＋€1.00 メディア追加料）– 12.4%', '電動工具 – 4.1%', 'キッチン家電 – 5.0%', 'ペットフード – 6.0%', 'キャンプ用品 – 10.8%', 'ファッション・スポーツ（€50超）– 13.0%', '寝具 – 14.1%', '美容・ケア – 15.0%', 'ジュエリー – 20.7%'],
        f: { div: '割合の計算対象' }, o: { incl: '税込価格', ex21: '税抜価格（付加価値税21%除く）', ex9: '税抜価格（付加価値税9%除く）' }, fee: { fixed: '1点ごとの固定額', surcharge: 'メディア追加料', commission: '変動手数料' },
        notes: ['1点ごとの固定額：€0.20（€10まで）、€0.40（€10〜20）、€0.85（€20超）；一部の電子機器は€20超で€2.48。メディア（本・ゲーム・音楽・映画）：＋€1.00。', 'カテゴリ別の割合は標準12.4%。すべて税別で、bolは手数料に21%の付加価値税を課します（課税事業者は控除可）。', '月額費用なし。売れたときだけ支払います。', '自社配送またはLVB（bolの物流）の費用は「送料（自己負担）」に入力してください。'],
        faq: [{ q: 'bolの手数料はいくら？', a: '販売1点ごとの固定額（€10まで€0.20、€10〜20は€0.40、€20超は€0.85、一部の電子機器は€2.48）に加え、カテゴリ別の割合：標準12.4%、4.1%（電動工具）〜20.7%（ジュエリー）。すべて税別。' }, { q: 'bolに月額費用はありますか？', a: 'ありません。bolでの販売に定額料金はなく、売れた商品の手数料のみです。' }, { q: '手数料に付加価値税はかかりますか？', a: 'はい、bolは手数料に21%を加算します。課税事業者は控除できるため費用になりません。それ以外は「費用になる」を選んでください。' }, { q: 'メディア追加料とは？', a: '本・ゲーム・音楽・映画は固定額と割合に加えて1点€1.00が追加されます。' }] },
      ko: { title: 'bol 수수료 계산기 2026 | 수수료·정산금·상품별 순이익', desc: '네덜란드·벨기에 bol.com 수수료 무료 계산: 가격 구간별 고정 수수료 + 카테고리별 4.1~20.7%, 수수료 부가세, 정산금·순이익·마진율·손익분기 판매가.', h1: 'bol 수수료 계산기 (2026년)', intro: 'bol(네덜란드/벨기에) 수수료는 두 부분입니다: 판매 건당 고정 금액(0.20~0.85€, 일부 전자제품은 더 높음) + 카테고리별 판매가 비율(기본 12.4%, 4.1~20.7%). 둘 다 부가세 별도. 계산기가 전부 합산해 정산금·순이익·손익분기 판매가를 보여줍니다.',
        cats: ['기본 (대부분 카테고리) – 12.4%', '전자제품 (20€ 초과 시 고정 2.48€) – 12.4%', '도서·게임·음악·영화 (+1.00€ 미디어 추가) – 12.4%', '전동공구 – 4.1%', '주방가전 – 5.0%', '반려동물 사료 – 6.0%', '캠핑용품 – 10.8%', '패션·스포츠 (50€ 초과) – 13.0%', '침구 – 14.1%', '뷰티·케어 – 15.0%', '주얼리 – 20.7%'],
        f: { div: '비율 계산 기준' }, o: { incl: '부가세 포함가', ex21: '부가세 21% 제외가', ex9: '부가세 9% 제외가' }, fee: { fixed: '건당 고정 수수료', surcharge: '미디어 추가 수수료', commission: '변동 수수료' },
        notes: ['건당 고정 수수료: 0.20€(10€까지), 0.40€(10~20€), 0.85€(20€ 초과); 일부 전자제품은 20€ 초과 시 2.48€. 미디어(도서·게임·음악·영화): +1.00€.', '카테고리별 비율, 기본 12.4%. 모든 금액 부가세 별도이며 bol은 수수료에 21% 부가세를 청구(매입세액공제 가능 시 환급).', '월 이용료 없음. 판매될 때만 지불.', '자체 배송비 또는 LVB(bol 물류) 비용은 “실제 배송비”에 입력하세요.'],
        faq: [{ q: 'bol 수수료는 얼마인가요?', a: '판매 건당 고정 금액(10€까지 0.20€, 10~20€ 0.40€, 20€ 초과 0.85€, 일부 전자제품 2.48€) + 카테고리별 비율: 기본 12.4%, 4.1%(전동공구)~20.7%(주얼리). 모두 부가세 별도.' }, { q: 'bol에 월 이용료가 있나요?', a: '없습니다. 구독료 없이 판매된 상품의 수수료만 냅니다.' }, { q: '수수료에 부가세가 붙나요?', a: '네, bol은 수수료에 21%를 추가합니다. 매입세액공제가 가능하면 환급되어 비용이 아닙니다. 아니면 “공제 불가” 옵션을 선택하세요.' }, { q: '미디어 추가 수수료란?', a: '도서·게임·음악·영화는 고정 금액과 비율에 더해 건당 1.00€가 추가됩니다.' }] }
    }
  });
})(typeof window !== 'undefined' ? window : global);
