(function (root) {
  var SF = root.SF, F = SF.F, n = SF.n;
  SF.add({
    id: 'coupang-kr', currency: 'KRW', flag: '🇰🇷', platform: 'Coupang', region: 'KR', countries: ['KR'], names: {ko: '쿠팡',ja: 'クーパン'},
    slug: { en: 'coupang-fee-calculator', de: 'coupang-gebuehrenrechner', fr: 'coupang-calculateur-commission', it: 'coupang-calcolo-commissioni', es: 'coupang-calculadora-comisiones', nl: 'coupang-commissie-berekenen', ja: 'coupang-fee-calculator', ko: 'coupang-fee-calculator' },
    fields: [F.price(29900), F.shipping(3000), F.cost(12000), F.shipCost(3000),
      F.cat(['5', '5.8', '7.8', '7.8', '7.8', '9.6', '10', '10', '10.5', '10.6', '10.8', '10.8', '10.8', '10.8', '10.8', '10.8', '10.8'], '10.5'), F.commission(10.5),
      { k: 'pay', l: 'pay', t: 'num', u: '%', d: 2.9, step: 0.1 }, F.vat(10),
      { k: 'svc', l: 'svc', t: 'sel', d: '0', o: [{ l: 'svc0', v: '0' }, { l: 'svc1', v: '55000' }] },
      F.orders(100), F.other(), F.target()],
    fees: function (v) {
      var base = n(v.price) + n(v.shipping);
      var com = base * n(v.commission) / 100, pay = base * n(v.pay) / 100;
      return [{ k: 'commission', a: com }, { k: 'pay', a: pay }, { k: 'vatOnFees', a: (com + pay) * n(v.vat) / 100 }, { k: 'svc', a: n(v.svc) / Math.max(1, n(v.orders)) }, { k: 'otherCost', a: base * n(v.other) / 100 }];
    },
    sources: [{ n: 'OSC: 쿠팡 판매자 수수료 2026 완벽정리', u: 'https://oscsnm.com/coupang-seller-fee-2026/' }, { n: '비젠소프트: 쿠팡 수수료 2026 개편', u: 'https://www.vizensoft.com/about/itinsight/read?no=742' }, { n: '퍼센티: 쿠팡 판매 수수료 및 마진 계산 방법', u: 'https://www.percenty.co.kr/blog/how-to-calculate-coupang-fee-and-margin' }, { n: '쿠팡 윙 판매자센터 (공식)', u: 'https://wing.coupang.com/' }],
    s: {
      en: { title: 'Coupang Fee Calculator 2026 – Commission, VAT, Real Payout', desc: 'Free Coupang seller fee calculator with 2026 rates: 4–10.9 % commission, the separate 2.9 % payment fee, VAT and monthly fee, payout and net profit.', h1: 'Coupang Fee Calculator (2026)', intro: 'Since the 2026 fee restructuring, Coupang shows the category commission (4–10.9 %) and the 2.9 % payment fee separately, and 10 % VAT is added on both. Sellers with monthly sales of ₩1M or more also pay a ₩55,000 monthly service fee. Pick a category and the rate is prefilled; the calculator shows payout, net profit and break-even price.',
        cats: ['Appliances & digital (TV, computers, tablets) – 5.0 %', 'Large appliances – 5.8 %', 'Audio & cameras – 7.8 %', 'Household goods – 7.8 %', 'Health & supplements – 7.8 %', 'Beauty – 9.6 %', 'Baby & kids – 10.0 %', 'Car accessories – 10.0 %', 'Fashion & accessories – 10.5 %', 'Food – 10.6 %', 'Books & music – 10.8 %', 'Stationery, toys, hobbies – 10.8 %', 'Sports & leisure – 10.8 %', 'Kitchenware – 10.8 %', 'Home interior & furniture – 10.8 %', 'Pet supplies – 10.8 %', 'Other – 10.8 %'],
        f: { pay: 'Payment fee %', svc: 'Monthly service fee' }, o: { svc0: 'Not applicable (monthly sales under ₩1M)', svc1: 'Applies (₩55,000/month)' }, fee: { commission: 'Sales commission', pay: 'Payment fee', svc: 'Monthly service fee (spread per order)' },
        notes: ['Fee base = the final amount paid by the customer (price + shipping, after discounts).', 'Sales commission (4–10.9 % by category) + 2.9 % payment fee, plus 10 % VAT on both. VAT-registered businesses can deduct it.', 'Monthly service fee of ₩55,000 (VAT incl.) when monthly sales reach ₩1M (₩5M for appliances/digital).', 'Rocket Growth logistics (inbound, delivery, storage) are extra. Confirm exact category rates in Coupang Wing announcements.'],
        faq: [{ q: 'What is the Coupang sales commission?', a: '4–10.9 % by category: appliances/digital 5–7.8 %, household goods and supplements 7.8 %, beauty 9.6 %, fashion 10.5 %, food 10.6 %, furniture, kitchen, toys and books 10.8 %. Since 2026 the 2.9 % payment fee is shown as a separate item.' }, { q: 'What amount are fees calculated on?', a: 'The final amount the customer actually paid (price + shipping, after coupons and discounts). Shipping is included in the base.' }, { q: 'How does VAT work?', a: '10 % VAT is charged on both the sales commission and the payment fee. VAT-registered businesses deduct it as input tax; simplified or exempt businesses bear it as a cost.' }, { q: 'When is the monthly service fee charged?', a: '₩55,000 (VAT incl.) once a month in any month where sales reach ₩1M (₩5M for appliances/digital). The calculator divides it by your monthly orders.' }] },
      de: { title: 'Coupang Gebührenrechner 2026 – Provision, Zahlungsgebühr, MwSt. und Marge', desc: 'Coupang (Korea) Marktplatzgebühren: Kategorieprovision (4–10,9 %), die seit 2026 separate Zahlungsgebühr 2,9 %, MwSt. auf Gebühren und Monatsservicegebühr – Auszahlung, Nettogewinn, Marge und Break-even-Preis kostenlos.', h1: 'Coupang Gebührenrechner (2026)', intro: 'Seit der Gebührenreform 2026 weist Coupang die Kategorieprovision (4–10,9 %) und die Zahlungsgebühr von 2,9 % getrennt aus; auf beide kommen 10 % MwSt. Händler mit Monatsumsatz ab ₩1 Mio. zahlen zusätzlich ₩55.000 Servicegebühr pro Monat. Kategorie wählen, Satz wird vorausgefüllt; der Rechner zeigt Auszahlung, Nettogewinn und Break-even-Preis.',
        cats: ['Elektronik & Digital (TV, Computer, Tablets) – 5,0 %', 'Großgeräte – 5,8 %', 'Audio & Kameras – 7,8 %', 'Haushaltswaren – 7,8 %', 'Gesundheit & Nahrungsergänzung – 7,8 %', 'Beauty – 9,6 %', 'Baby & Kinder – 10,0 %', 'Autozubehör – 10,0 %', 'Mode & Accessoires – 10,5 %', 'Lebensmittel – 10,6 %', 'Bücher & Musik – 10,8 %', 'Schreibwaren, Spielzeug, Hobby – 10,8 %', 'Sport & Freizeit – 10,8 %', 'Küche – 10,8 %', 'Wohnen & Möbel – 10,8 %', 'Tierbedarf – 10,8 %', 'Sonstiges – 10,8 %'],
        f: { pay: 'Zahlungsgebühr %', svc: 'Monatliche Servicegebühr' }, o: { svc0: 'Entfällt (Monatsumsatz unter ₩1 Mio.)', svc1: 'Fällig (₩55.000/Monat)' }, fee: { commission: 'Verkaufsprovision', pay: 'Zahlungsgebühr', svc: 'Monatliche Servicegebühr (umgelegt)' },
        notes: ['Gebührenbasis = vom Kunden tatsächlich gezahlter Endbetrag (Preis + Versand, nach Rabatten).', 'Verkaufsprovision (4–10,9 % je Kategorie) + 2,9 % Zahlungsgebühr, auf beide 10 % MwSt. Vorsteuerabzugsberechtigte holen sie zurück.', 'Monatliche Servicegebühr ₩55.000 (inkl. MwSt.) ab ₩1 Mio. Monatsumsatz (₩5 Mio. bei Elektronik/Digital).', 'Rocket-Growth-Logistik (Einlagerung, Versand, Lagerung) extra. Genaue Kategoriesätze in den Coupang-Wing-Mitteilungen prüfen.'],
        faq: [{ q: 'Wie hoch ist die Coupang-Verkaufsprovision?', a: '4–10,9 % je Kategorie: Elektronik/Digital 5–7,8 %, Haushaltswaren und Nahrungsergänzung 7,8 %, Beauty 9,6 %, Mode 10,5 %, Lebensmittel 10,6 %, Möbel, Küche, Spielzeug und Bücher 10,8 %. Seit 2026 wird die Zahlungsgebühr von 2,9 % separat ausgewiesen.' }, { q: 'Worauf werden die Gebühren berechnet?', a: 'Auf den vom Kunden tatsächlich gezahlten Endbetrag (Preis + Versand, nach Gutscheinen und Rabatten). Versand gehört zur Basis.' }, { q: 'Wie funktioniert die MwSt.?', a: '10 % MwSt. auf Verkaufsprovision und Zahlungsgebühr. Vorsteuerabzugsberechtigte Unternehmen ziehen sie ab; Kleinunternehmer oder steuerbefreite tragen sie als Kosten.' }, { q: 'Wann fällt die monatliche Servicegebühr an?', a: '₩55.000 (inkl. MwSt.) einmal pro Monat, wenn der Umsatz ₩1 Mio. erreicht (₩5 Mio. bei Elektronik/Digital). Der Rechner teilt sie durch deine Bestellungen pro Monat.' }] },
      fr: { title: 'Calculateur de frais Coupang 2026 – commission, frais de paiement, TVA et marge', desc: 'Frais de la marketplace Coupang (Corée) : commission par catégorie (4–10,9 %), frais de paiement 2,9 % séparés depuis 2026, TVA sur les frais et frais de service mensuels – montant reversé, bénéfice net, marge et prix d’équilibre gratuitement.', h1: 'Calculateur de frais Coupang (2026)', intro: 'Depuis la réforme des frais 2026, Coupang affiche séparément la commission par catégorie (4–10,9 %) et les frais de paiement de 2,9 %, avec 10 % de TVA sur les deux. Les vendeurs réalisant ₩1 M de ventes mensuelles ou plus paient aussi ₩55 000 de frais de service par mois. Choisissez une catégorie, le taux se préremplit ; le calculateur affiche montant reversé, bénéfice net et prix d’équilibre.',
        cats: ['Électronique & digital (TV, ordinateurs, tablettes) – 5,0 %', 'Gros électroménager – 5,8 %', 'Audio & appareils photo – 7,8 %', 'Articles ménagers – 7,8 %', 'Santé & compléments – 7,8 %', 'Beauté – 9,6 %', 'Bébé & enfants – 10,0 %', 'Accessoires auto – 10,0 %', 'Mode & accessoires – 10,5 %', 'Alimentaire – 10,6 %', 'Livres & musique – 10,8 %', 'Papeterie, jouets, loisirs – 10,8 %', 'Sport & loisirs – 10,8 %', 'Cuisine – 10,8 %', 'Décoration & meubles – 10,8 %', 'Animalerie – 10,8 %', 'Autre – 10,8 %'],
        f: { pay: 'Frais de paiement %', svc: 'Frais de service mensuels' }, o: { svc0: 'Non applicable (ventes mensuelles sous ₩1 M)', svc1: 'Applicable (₩55 000/mois)' }, fee: { commission: 'Commission de vente', pay: 'Frais de paiement', svc: 'Frais de service mensuels (répartis)' },
        notes: ['Base des frais = montant final réellement payé par le client (prix + port, après remises).', 'Commission de vente (4–10,9 % selon catégorie) + 2,9 % de frais de paiement, plus 10 % de TVA sur les deux. Les entreprises assujetties la récupèrent.', 'Frais de service mensuels de ₩55 000 (TVA incluse) dès ₩1 M de ventes mensuelles (₩5 M pour l’électronique/digital).', 'Logistique Rocket Growth (entrée, livraison, stockage) en plus. Vérifiez les taux exacts par catégorie dans les annonces Coupang Wing.'],
        faq: [{ q: 'Quelle est la commission de vente Coupang ?', a: '4 à 10,9 % selon la catégorie : électronique/digital 5–7,8 %, articles ménagers et compléments 7,8 %, beauté 9,6 %, mode 10,5 %, alimentaire 10,6 %, meubles, cuisine, jouets et livres 10,8 %. Depuis 2026, les frais de paiement de 2,9 % sont affichés séparément.' }, { q: 'Sur quel montant les frais sont-ils calculés ?', a: 'Sur le montant final réellement payé par le client (prix + port, après coupons et remises). Le port fait partie de la base.' }, { q: 'Comment fonctionne la TVA ?', a: '10 % de TVA s’appliquent à la commission de vente et aux frais de paiement. Les entreprises assujetties la déduisent ; les régimes simplifiés ou exonérés la supportent comme un coût.' }, { q: 'Quand les frais de service mensuels sont-ils facturés ?', a: '₩55 000 (TVA incluse) une fois par mois dès que les ventes atteignent ₩1 M (₩5 M pour l’électronique/digital). Le calculateur les divise par vos commandes mensuelles.' }] },
      it: { title: 'Calcolatore commissioni Coupang 2026 – commissione, costo pagamento, IVA e margine', desc: 'Commissioni del marketplace Coupang (Corea): commissione per categoria (4–10,9 %), costo di pagamento 2,9 % separato dal 2026, IVA sulle commissioni e canone di servizio mensile – accredito, profitto netto, margine e prezzo di pareggio gratis.', h1: 'Calcolatore commissioni Coupang (2026)', intro: 'Dalla riforma delle commissioni 2026, Coupang mostra separatamente la commissione per categoria (4–10,9 %) e il costo di pagamento del 2,9 %, con il 10 % di IVA su entrambi. I venditori con vendite mensili da ₩1 M in su pagano anche ₩55.000 di canone di servizio al mese. Scegli la categoria e l’aliquota si precompila; il calcolatore mostra accredito, profitto netto e prezzo di pareggio.',
        cats: ['Elettronica & digitale (TV, computer, tablet) – 5,0 %', 'Grandi elettrodomestici – 5,8 %', 'Audio & fotocamere – 7,8 %', 'Casalinghi – 7,8 %', 'Salute & integratori – 7,8 %', 'Beauty – 9,6 %', 'Bambini – 10,0 %', 'Accessori auto – 10,0 %', 'Moda & accessori – 10,5 %', 'Alimentari – 10,6 %', 'Libri & musica – 10,8 %', 'Cancelleria, giocattoli, hobby – 10,8 %', 'Sport & tempo libero – 10,8 %', 'Cucina – 10,8 %', 'Arredamento & mobili – 10,8 %', 'Animali – 10,8 %', 'Altro – 10,8 %'],
        f: { pay: 'Costo di pagamento %', svc: 'Canone di servizio mensile' }, o: { svc0: 'Non applicabile (vendite mensili sotto ₩1 M)', svc1: 'Applicabile (₩55.000/mese)' }, fee: { commission: 'Commissione di vendita', pay: 'Costo di pagamento', svc: 'Canone di servizio mensile (ripartito)' },
        notes: ['Base delle commissioni = importo finale effettivamente pagato dal cliente (prezzo + spedizione, dopo gli sconti).', 'Commissione di vendita (4–10,9 % per categoria) + 2,9 % di costo di pagamento, più 10 % di IVA su entrambi. Le imprese con IVA detraibile la recuperano.', 'Canone di servizio mensile di ₩55.000 (IVA inclusa) da ₩1 M di vendite mensili (₩5 M per elettronica/digitale).', 'Logistica Rocket Growth (ingresso, consegna, stoccaggio) a parte. Verifica le aliquote esatte per categoria negli avvisi di Coupang Wing.'],
        faq: [{ q: 'Qual è la commissione di vendita Coupang?', a: '4–10,9 % per categoria: elettronica/digitale 5–7,8 %, casalinghi e integratori 7,8 %, beauty 9,6 %, moda 10,5 %, alimentari 10,6 %, mobili, cucina, giocattoli e libri 10,8 %. Dal 2026 il costo di pagamento del 2,9 % è indicato separatamente.' }, { q: 'Su quale importo si calcolano le commissioni?', a: 'Sull’importo finale effettivamente pagato dal cliente (prezzo + spedizione, dopo coupon e sconti). La spedizione fa parte della base.' }, { q: 'Come funziona l’IVA?', a: 'Il 10 % di IVA si applica sia alla commissione di vendita sia al costo di pagamento. Le imprese con IVA detraibile la recuperano; i regimi semplificati o esenti la sostengono come costo.' }, { q: 'Quando viene addebitato il canone di servizio mensile?', a: '₩55.000 (IVA inclusa) una volta al mese nei mesi in cui le vendite raggiungono ₩1 M (₩5 M per elettronica/digitale). Il calcolatore lo divide per i tuoi ordini mensili.' }] },
      es: { title: 'Calculadora de tarifas Coupang 2026 – comisión, tarifa de pago, IVA y margen', desc: 'Tarifas del marketplace Coupang (Corea): comisión por categoría (4–10,9 %), tarifa de pago del 2,9 % separada desde 2026, IVA sobre las tarifas y cuota de servicio mensual – importe recibido, beneficio neto, margen y precio de equilibrio gratis.', h1: 'Calculadora de tarifas Coupang (2026)', intro: 'Desde la reforma de tarifas de 2026, Coupang muestra por separado la comisión por categoría (4–10,9 %) y la tarifa de pago del 2,9 %, con un 10 % de IVA sobre ambas. Los vendedores con ventas mensuales de ₩1 M o más pagan además ₩55.000 de cuota de servicio al mes. Elige una categoría y la tarifa se precarga; la calculadora muestra importe recibido, beneficio neto y precio de equilibrio.',
        cats: ['Electrónica y digital (TV, ordenadores, tablets) – 5,0 %', 'Grandes electrodomésticos – 5,8 %', 'Audio y cámaras – 7,8 %', 'Artículos del hogar – 7,8 %', 'Salud y suplementos – 7,8 %', 'Belleza – 9,6 %', 'Bebé y niños – 10,0 %', 'Accesorios de coche – 10,0 %', 'Moda y accesorios – 10,5 %', 'Alimentación – 10,6 %', 'Libros y música – 10,8 %', 'Papelería, juguetes, hobbies – 10,8 %', 'Deporte y ocio – 10,8 %', 'Cocina – 10,8 %', 'Decoración y muebles – 10,8 %', 'Mascotas – 10,8 %', 'Otros – 10,8 %'],
        f: { pay: 'Tarifa de pago %', svc: 'Cuota de servicio mensual' }, o: { svc0: 'No aplica (ventas mensuales por debajo de ₩1 M)', svc1: 'Aplica (₩55.000/mes)' }, fee: { commission: 'Comisión de venta', pay: 'Tarifa de pago', svc: 'Cuota de servicio mensual (repartida)' },
        notes: ['Base de las tarifas = importe final realmente pagado por el cliente (precio + envío, tras descuentos).', 'Comisión de venta (4–10,9 % por categoría) + 2,9 % de tarifa de pago, más 10 % de IVA sobre ambas. Las empresas con IVA deducible lo recuperan.', 'Cuota de servicio mensual de ₩55.000 (IVA incl.) a partir de ₩1 M de ventas mensuales (₩5 M en electrónica/digital).', 'La logística Rocket Growth (entrada, entrega, almacenamiento) es aparte. Comprueba las tarifas exactas por categoría en los avisos de Coupang Wing.'],
        faq: [{ q: '¿Cuál es la comisión de venta de Coupang?', a: '4–10,9 % según categoría: electrónica/digital 5–7,8 %, artículos del hogar y suplementos 7,8 %, belleza 9,6 %, moda 10,5 %, alimentación 10,6 %, muebles, cocina, juguetes y libros 10,8 %. Desde 2026 la tarifa de pago del 2,9 % se muestra por separado.' }, { q: '¿Sobre qué importe se calculan las tarifas?', a: 'Sobre el importe final que realmente pagó el cliente (precio + envío, tras cupones y descuentos). El envío forma parte de la base.' }, { q: '¿Cómo funciona el IVA?', a: 'Se cobra un 10 % de IVA tanto sobre la comisión de venta como sobre la tarifa de pago. Las empresas con IVA deducible lo recuperan; los regímenes simplificados o exentos lo asumen como coste.' }, { q: '¿Cuándo se cobra la cuota de servicio mensual?', a: '₩55.000 (IVA incl.) una vez al mes en los meses en que las ventas alcanzan ₩1 M (₩5 M en electrónica/digital). La calculadora la divide entre tus pedidos mensuales.' }] },
      nl: { title: 'Coupang commissie berekenen 2026 – commissie, betalingskosten, btw en marge', desc: 'Coupang (Korea) marketplace-kosten: categoriecommissie (4–10,9 %), de sinds 2026 aparte betalingskosten van 2,9 %, btw over kosten en maandelijkse servicekosten – uitbetaling, nettowinst, marge en break-evenprijs gratis.', h1: 'Coupang commissie berekenen (2026)', intro: 'Sinds de kostenhervorming van 2026 toont Coupang de categoriecommissie (4–10,9 %) en de betalingskosten van 2,9 % apart, met 10 % btw over beide. Verkopers met een maandomzet vanaf ₩1 mln betalen daarnaast ₩55.000 servicekosten per maand. Kies een categorie en het tarief wordt ingevuld; de calculator toont uitbetaling, nettowinst en break-evenprijs.',
        cats: ['Elektronica & digitaal (tv, computers, tablets) – 5,0 %', 'Grote apparaten – 5,8 %', 'Audio & camera’s – 7,8 %', 'Huishoudelijke artikelen – 7,8 %', 'Gezondheid & supplementen – 7,8 %', 'Beauty – 9,6 %', 'Baby & kind – 10,0 %', 'Auto-accessoires – 10,0 %', 'Mode & accessoires – 10,5 %', 'Food – 10,6 %', 'Boeken & muziek – 10,8 %', 'Kantoor, speelgoed, hobby – 10,8 %', 'Sport & vrije tijd – 10,8 %', 'Keuken – 10,8 %', 'Wonen & meubels – 10,8 %', 'Dierbenodigdheden – 10,8 %', 'Overig – 10,8 %'],
        f: { pay: 'Betalingskosten %', svc: 'Maandelijkse servicekosten' }, o: { svc0: 'Niet van toepassing (maandomzet onder ₩1 mln)', svc1: 'Van toepassing (₩55.000/maand)' }, fee: { commission: 'Verkoopcommissie', pay: 'Betalingskosten', svc: 'Maandelijkse servicekosten (omgeslagen)' },
        notes: ['Kostenbasis = het door de klant werkelijk betaalde eindbedrag (prijs + verzending, na kortingen).', 'Verkoopcommissie (4–10,9 % per categorie) + 2,9 % betalingskosten, plus 10 % btw over beide. Btw-plichtige bedrijven vragen die terug.', 'Maandelijkse servicekosten ₩55.000 (incl. btw) vanaf ₩1 mln maandomzet (₩5 mln voor elektronica/digitaal).', 'Rocket Growth-logistiek (inslag, bezorging, opslag) komt erbij. Controleer exacte categorietarieven in de Coupang Wing-mededelingen.'],
        faq: [{ q: 'Hoe hoog is de verkoopcommissie van Coupang?', a: '4–10,9 % per categorie: elektronica/digitaal 5–7,8 %, huishoudelijke artikelen en supplementen 7,8 %, beauty 9,6 %, mode 10,5 %, food 10,6 %, meubels, keuken, speelgoed en boeken 10,8 %. Sinds 2026 worden de betalingskosten van 2,9 % apart getoond.' }, { q: 'Waarover worden de kosten berekend?', a: 'Over het eindbedrag dat de klant werkelijk betaalde (prijs + verzending, na coupons en kortingen). Verzending hoort bij de basis.' }, { q: 'Hoe werkt de btw?', a: '10 % btw over zowel de verkoopcommissie als de betalingskosten. Btw-plichtige bedrijven trekken die af; vereenvoudigde of vrijgestelde regimes dragen die als kosten.' }, { q: 'Wanneer worden de maandelijkse servicekosten gerekend?', a: '₩55.000 (incl. btw) eenmaal per maand in maanden waarin de omzet ₩1 mln bereikt (₩5 mln voor elektronica/digitaal). De calculator deelt ze door je bestellingen per maand.' }] },
      ja: { title: 'Coupang（クーパン）手数料計算ツール 2026｜販売手数料・決済手数料・付加価値税・利益', desc: '韓国Coupangマーケットプレイスの手数料：カテゴリ別販売手数料（4〜10.9%）、2026年に分離された決済手数料2.9%、手数料の付加価値税、月額サービス料を反映し、入金額・純利益・利益率・損益分岐価格を無料計算。', h1: 'Coupang（クーパン）手数料計算ツール（2026年版）', intro: '2026年の手数料改定により、Coupangはカテゴリ別販売手数料（4〜10.9%）と決済手数料2.9%を分けて表示し、両方に付加価値税10%が加算されます。月商100万ウォン以上の出品者は月額サービス料55,000ウォンも支払います。カテゴリを選ぶと料率が自動入力され、入金額・純利益・損益分岐価格が表示されます。',
        cats: ['家電・デジタル（テレビ・PC・タブレット）– 5.0%', '大型家電 – 5.8%', 'オーディオ・カメラ – 7.8%', '生活用品 – 7.8%', '健康・サプリ – 7.8%', 'ビューティー – 9.6%', 'ベビー・キッズ – 10.0%', 'カー用品 – 10.0%', 'ファッション・雑貨 – 10.5%', '食品 – 10.6%', '書籍・音楽 – 10.8%', '文具・玩具・ホビー – 10.8%', 'スポーツ・レジャー – 10.8%', 'キッチン用品 – 10.8%', 'インテリア・家具 – 10.8%', 'ペット用品 – 10.8%', 'その他 – 10.8%'],
        f: { pay: '決済手数料 %', svc: '月額サービス料' }, o: { svc0: '対象外（月商100万ウォン未満）', svc1: '対象（月55,000ウォン）' }, fee: { commission: '販売手数料', pay: '決済手数料', svc: '月額サービス料（按分）' },
        notes: ['手数料の基準額 ＝ 顧客が実際に支払った最終金額（価格＋送料、割引適用後）。', '販売手数料（カテゴリ別4〜10.9%）＋決済手数料2.9%、両方に付加価値税10%。課税事業者は控除可。', '月商100万ウォン以上（家電・デジタルは500万ウォン）で月額サービス料55,000ウォン（税込）。', 'ロケットグロース物流（入庫・配送・保管）は別途。正確なカテゴリ別料率はCoupang Wingのお知らせで確認。'],
        faq: [{ q: 'Coupangの販売手数料は？', a: 'カテゴリ別4〜10.9%：家電・デジタル5〜7.8%、生活用品・サプリ7.8%、ビューティー9.6%、ファッション10.5%、食品10.6%、家具・キッチン・玩具・書籍10.8%。2026年から決済手数料2.9%が別項目で表示されます。' }, { q: '手数料は何に対して計算されますか？', a: '顧客が実際に支払った最終金額（価格＋送料、クーポン・割引適用後）です。送料も対象に含まれます。' }, { q: '付加価値税はどうなりますか？', a: '販売手数料と決済手数料の両方に10%がかかります。課税事業者は仕入税額控除できますが、簡易課税・免税事業者は費用になります。' }, { q: '月額サービス料はいつ請求されますか？', a: '月商が100万ウォン（家電・デジタルは500万ウォン）に達した月に、月1回55,000ウォン（税込）。計算ツールでは月間注文数で按分しています。' }] },
      ko: { title: '쿠팡 수수료 계산기 2026 | 판매수수료·결제수수료·부가세·마진 자동 계산', desc: '쿠팡 마켓플레이스 카테고리별 판매수수료(4~10.9%), 2026년 분리된 결제수수료 2.9%, 부가세, 월 서비스 이용료까지 반영해 정산금액·순이익·마진율·손익분기 판매가를 무료로 계산합니다.', h1: '쿠팡 수수료 계산기 (2026년)', intro: '2026년 쿠팡 수수료 개편으로 판매수수료(카테고리별 4~10.9%)와 결제수수료(2.9%)가 분리 표기되고, 두 수수료에 부가세 10%가 별도로 붙습니다. 월 매출 100만원 이상이면 월 55,000원의 서비스 이용료도 추가됩니다. 카테고리만 고르면 수수료율이 자동 입력되고 정산금액·순이익·손익분기 판매가가 바로 계산됩니다.',
        cats: ['가전·디지털 (TV·컴퓨터·태블릿) – 5.0%', '대형가전 – 5.8%', '음향·카메라 – 7.8%', '생활용품 – 7.8%', '헬스·건강식품 – 7.8%', '뷰티 – 9.6%', '출산·유아동 – 10.0%', '자동차용품 – 10.0%', '패션의류·잡화 – 10.5%', '식품 – 10.6%', '도서·음반 – 10.8%', '문구·완구·취미 – 10.8%', '스포츠·레저 – 10.8%', '주방용품 – 10.8%', '홈인테리어·가구 – 10.8%', '반려동물용품 – 10.8%', '기타 – 10.8%'],
        f: { pay: '결제수수료 %', svc: '월 서비스 이용료' }, o: { svc0: '해당 없음 (월 매출 100만원 미만)', svc1: '적용 (월 55,000원)' }, fee: { commission: '판매수수료', pay: '결제수수료', svc: '월 서비스 이용료 (주문당 배분)' },
        notes: ['수수료 기준 금액 = 고객 최종 결제금액(판매가 + 배송비, 할인 적용 후).', '판매수수료(카테고리별 4~10.9%) + 결제수수료 2.9%, 여기에 부가세 10% 별도. 일반과세자는 매입세액공제 가능.', '월 매출 100만원 이상(가전·디지털은 500만원) 시 월 서비스 이용료 55,000원(VAT 포함).', '로켓그로스 이용 시 입출고·배송·보관비 별도. 카테고리별 정확한 요율은 쿠팡 윙 공지에서 확인.'],
        faq: [{ q: '쿠팡 판매수수료는 몇 %인가요?', a: '카테고리별 4~10.9%입니다. 가전·디지털 5~7.8%, 생활용품·건강식품 7.8%, 뷰티 9.6%, 패션 10.5%, 식품 10.6%, 가구·주방·완구·도서 10.8% 수준이며, 2026년부터 결제수수료 2.9%가 별도 항목으로 표기됩니다.' }, { q: '수수료는 어떤 금액을 기준으로 계산되나요?', a: '고객이 실제 결제한 최종 금액(판매가 + 배송비, 쿠폰·할인 적용 후)입니다. 판매가만이 아니라 배송비에도 수수료가 붙습니다.' }, { q: '부가세는 어떻게 되나요?', a: '판매수수료와 결제수수료에 부가세 10%가 별도로 부과됩니다. 일반과세자는 매입세액공제로 돌려받지만 간이과세자·면세사업자는 그대로 비용이 됩니다.' }, { q: '월 서비스 이용료는 언제 내나요?', a: '월 매출 100만원 이상(가전·디지털 카테고리는 500만원 이상)인 달에 55,000원(VAT 포함)이 월 1회 부과됩니다. 계산기는 이 금액을 월 주문 수로 나눠 주문 1건당 부담으로 표시합니다.' }] }
    }
  });
})(typeof window !== 'undefined' ? window : global);
