(function (root) {
  var SF = root.SF, F = SF.F, n = SF.n;
  SF.add({
    id: 'fnac-fr', currency: 'EUR', flag: '🇫🇷', platform: 'Fnac Marketplace', region: 'FR', countries: ['FR'],
    slug: { en: 'fnac-fee-calculator', de: 'fnac-gebuehrenrechner', fr: 'fnac-calculateur-commission', it: 'fnac-calcolo-commissioni', es: 'fnac-calculadora-comisiones', nl: 'fnac-commissie-berekenen', ja: 'fnac-fee-calculator', ko: 'fnac-fee-calculator' },
    fields: [F.price(59.90), F.shipping(4.99), F.cost(30), F.shipCost(4.5),
      F.cat(['7|8|10', '6|10|10', '6.5|10|10', '7|10|10', '8|10|10', '8|8|10', '8|10|10', '13|16|16', '12|16|16', '12|16|16', '12|15|15', '14|15|15', '15|15|15', '15|15|15'], '7|8|10'),
      { k: 'cond', l: 'cond', t: 'sel', d: '0', o: [{ l: 'new', v: '0' }, { l: 'refurb', v: '1' }, { l: 'used', v: '2' }] },
      F.commission(7), { k: 'sub', l: 'sub', t: 'num', u: 'cur', d: 49.99 }, { k: 'perOrder', l: 'perOrder', t: 'num', u: 'cur', d: 0.99 },
      F.orders(60), F.vat(20), F.other(), F.target()],
    fees: function (v) {
      var base = n(v.price) + n(v.shipping);
      var com = base * n(v.commission) / 100, sub = n(v.sub) / Math.max(1, n(v.orders)), po = n(v.perOrder);
      return [{ k: 'commission', a: com }, { k: 'perOrder', a: po }, { k: 'sub', a: sub }, { k: 'vatOnFees', a: (com + sub + po) * n(v.vat) / 100 }, { k: 'otherCost', a: base * n(v.other) / 100 }];
    },
    sources: [{ n: 'DocShipper : vendre sur Fnac Marketplace 2026, frais', u: 'https://sourcing.docshipper.com/e-commerce/vendre-fnac/' }, { n: 'Qashflo : commissions et frais de vente Fnac', u: 'https://qashflo.eu/guides-marketplaces/fnac/frais-de-vente-fnac/' }, { n: 'Margeo : Fnac Marketplace 2026, frais vendeur', u: 'https://margeoapp.com/blog/vendre-sur-fnac-marketplace-revendeur' }],
    s: {
      en: { title: 'Fnac Marketplace Fee Calculator 2026 – Seller Fees, Profit', desc: 'Free Fnac Marketplace fee calculator: 6–16 % commission by category and condition — new, refurbished or used — plus subscription, per-order fee, payout.', h1: 'Fnac Marketplace Fee Calculator (2026)', intro: 'On Fnac Marketplace (France) the commission depends on category and condition: from 6 % (new TVs, hard drives) to 16 % (refurbished or used accessories). Add a professional monthly subscription and a fixed fee per order. The calculator combines everything to show commission, payout and net profit per sale.',
        cats: ['Computers & tablets – 7 / 8 / 10 %', 'Hard drives, TV, projectors – 6 / 10 / 10 %', 'Large appliances – 6.5 / 10 / 10 %', 'Cameras & lenses – 7 / 10 / 10 %', 'Small appliances – 8 / 10 / 10 %', 'Smartphones – 8 / 8 / 10 %', 'Audio, DJ – 8 / 10 / 10 %', 'Gaming accessories – 13 / 16 / 16 %', 'Tech accessories – 12 / 16 / 16 %', 'Toys, games, health – 12 / 16 / 16 %', 'Books – 12 / 15 / 15 %', 'Sports & luggage – 14 / 15 / 15 %', 'Home textiles – 15 %', 'Furniture – 15 %'],
        cond: ['New', 'Refurbished', 'Used'], f: { cond: 'Condition', sub: 'Monthly subscription (ex VAT)', perOrder: 'Fixed fee per order' }, o: { new: 'New', refurb: 'Refurbished', used: 'Used' }, fee: { commission: 'Fnac commission', perOrder: 'Fixed fee per order', sub: 'Subscription per order' },
        notes: ['Rate by category and condition: e.g. computers & tablets 7 % (new) / 8 % (refurbished) / 10 % (used), books 12 / 15 / 15 %, furniture 15 %.', 'Professional subscription: €39.90 to €49.99 ex VAT per month depending on 2026 sources – check your seller account and adjust the field.', 'Several guides report a payment fee of about €0.99 per order and €2 per return; change it if your contract differs.', 'Commission base: price incl. VAT + shipping according to our sources; sales are paid out 11 to 30 days after delivery.'],
        faq: [{ q: 'What is the Fnac Marketplace commission?', a: 'From 6 % to 16 % depending on category and product condition. Examples: laptops 7 % new, 8 % refurbished, 10 % used; books 12 % new, 15 % used; furniture and home textiles 15 %.' }, { q: 'How much is the Fnac seller subscription?', a: '2026 guides quote €39.90 to €49.99 ex VAT per month. The exact amount is in your contract: adjust the “monthly subscription” field if needed.' }, { q: 'Are there fees per order?', a: 'Several guides mention about €0.99 payment fee per order and €2 processing fee per return. Both are editable in the calculator.' }, { q: 'When do I get paid?', a: 'Payment is made 11 days after confirmed delivery for established sellers, up to 30 days for new sellers.' }] },
      de: { title: 'Fnac Marketplace Gebührenrechner 2026 – Händlergebühren & Marge', desc: 'Fnac-Marketplace-Gebühren berechnen: 6–16 % Provision je Kategorie und Zustand (neu, refurbished, gebraucht), Monatsabo, Gebühr pro Bestellung, Auszahlung und Nettogewinn.', h1: 'Fnac Marketplace Gebührenrechner (2026)', intro: 'Auf Fnac Marketplace (Frankreich) hängt die Provision von Kategorie und Zustand ab: von 6 % (neue TVs, Festplatten) bis 16 % (refurbished oder gebrauchtes Zubehör). Dazu kommen ein Monatsabo für Profihändler und eine feste Gebühr pro Bestellung. Der Rechner kombiniert alles und zeigt Provision, Auszahlung und Nettogewinn pro Verkauf.',
        cats: ['Computer & Tablets – 7 / 8 / 10 %', 'Festplatten, TV, Beamer – 6 / 10 / 10 %', 'Großgeräte – 6,5 / 10 / 10 %', 'Kameras & Objektive – 7 / 10 / 10 %', 'Kleingeräte – 8 / 10 / 10 %', 'Smartphones – 8 / 8 / 10 %', 'Audio, DJ – 8 / 10 / 10 %', 'Gaming-Zubehör – 13 / 16 / 16 %', 'Tech-Zubehör – 12 / 16 / 16 %', 'Spielzeug, Spiele, Gesundheit – 12 / 16 / 16 %', 'Bücher – 12 / 15 / 15 %', 'Sport & Gepäck – 14 / 15 / 15 %', 'Heimtextilien – 15 %', 'Möbel – 15 %'],
        cond: ['Neu', 'Refurbished', 'Gebraucht'], f: { cond: 'Zustand', sub: 'Monatsabo (netto)', perOrder: 'Feste Gebühr pro Bestellung' }, o: { new: 'Neu', refurb: 'Refurbished', used: 'Gebraucht' }, fee: { commission: 'Fnac-Provision', perOrder: 'Gebühr pro Bestellung', sub: 'Abo / Bestellung' },
        notes: ['Satz nach Kategorie und Zustand: z. B. Computer & Tablets 7 % (neu) / 8 % (refurbished) / 10 % (gebraucht), Bücher 12 / 15 / 15 %, Möbel 15 %.', 'Profi-Abo: 39,90 bis 49,99 € netto pro Monat je nach Quelle 2026 – im Händlerkonto prüfen und Feld anpassen.', 'Mehrere Guides nennen ca. 0,99 € Zahlungsgebühr pro Bestellung und 2 € pro Retoure; bei abweichendem Vertrag ändern.', 'Provisionsbasis laut unseren Quellen: Brutto-Preis + Versand; Auszahlung 11 bis 30 Tage nach Lieferung.'],
        faq: [{ q: 'Wie hoch ist die Fnac-Marketplace-Provision?', a: '6 % bis 16 % je nach Kategorie und Zustand. Beispiele: Laptops 7 % neu, 8 % refurbished, 10 % gebraucht; Bücher 12 % neu, 15 % gebraucht; Möbel und Heimtextilien 15 %.' }, { q: 'Was kostet das Fnac-Händlerabo?', a: 'Guides aus 2026 nennen 39,90 bis 49,99 € netto pro Monat. Der genaue Betrag steht in deinem Vertrag: Feld „Monatsabo“ bei Bedarf anpassen.' }, { q: 'Gibt es Gebühren pro Bestellung?', a: 'Mehrere Guides nennen ca. 0,99 € Zahlungsgebühr pro Bestellung und 2 € Bearbeitungsgebühr pro Retoure. Beides ist im Rechner editierbar.' }, { q: 'Wann wird ausgezahlt?', a: '11 Tage nach bestätigter Lieferung bei etablierten Händlern, bis zu 30 Tage bei neuen Händlern.' }] },
      fr: { title: 'Calculateur de commission Fnac Marketplace 2026 – frais vendeur et marge', desc: 'Calculez vos frais Fnac Marketplace : commission 6–16 % selon catégorie et état (neuf, reconditionné, occasion), abonnement mensuel, frais par commande, montant reversé et bénéfice net.', h1: 'Calculateur de commission Fnac Marketplace (2026)', intro: 'Sur Fnac Marketplace, la commission dépend de la catégorie et de l’état du produit : de 6 % (TV, disques durs neufs) à 16 % (accessoires reconditionnés ou d’occasion). S’y ajoutent un abonnement mensuel professionnel et des frais fixes par commande. Le calculateur combine le tout pour afficher commission, montant reversé et bénéfice net par vente.',
        cats: ['Ordinateurs & tablettes – 7 / 8 / 10 %', 'Disques durs, TV, vidéoprojecteurs – 6 / 10 / 10 %', 'Gros électroménager – 6,5 / 10 / 10 %', 'Photo & objectifs – 7 / 10 / 10 %', 'Petit électroménager – 8 / 10 / 10 %', 'Smartphones – 8 / 8 / 10 %', 'Audio, DJ – 8 / 10 / 10 %', 'Accessoires gaming – 13 / 16 / 16 %', 'Accessoires high-tech – 12 / 16 / 16 %', 'Jouets, jeux, santé – 12 / 16 / 16 %', 'Livres – 12 / 15 / 15 %', 'Sport & bagagerie – 14 / 15 / 15 %', 'Linge de maison – 15 %', 'Meubles – 15 %'],
        cond: ['Neuf', 'Reconditionné', 'Occasion'], f: { cond: 'État', sub: 'Abonnement mensuel HT', perOrder: 'Frais fixes par commande' }, o: { new: 'Neuf', refurb: 'Reconditionné', used: 'Occasion' }, fee: { commission: 'Commission Fnac', perOrder: 'Frais fixes par commande', sub: 'Abonnement / commande' },
        notes: ['Taux selon catégorie et état : ex. ordinateurs & tablettes 7 % (neuf) / 8 % (reconditionné) / 10 % (occasion), livres 12 / 15 / 15 %, meubles 15 %.', 'Abonnement professionnel : 39,90 à 49,99 € HT/mois selon les sources 2026 – vérifiez dans votre espace vendeur et ajustez le champ.', 'Frais de paiement d’environ 0,99 € par commande et 2 € par retour signalés par plusieurs guides ; modifiez si votre contrat diffère.', 'Base de commission : prix TTC + frais de port selon nos sources ; paiement des ventes sous 11 à 30 jours après livraison.'],
        faq: [{ q: 'Quelle est la commission Fnac Marketplace ?', a: 'De 6 % à 16 % selon la catégorie et l’état du produit. Exemples : ordinateurs portables 7 % neuf, 8 % reconditionné, 10 % occasion ; livres 12 % neuf, 15 % occasion ; meubles et linge de maison 15 %.' }, { q: 'Combien coûte l’abonnement vendeur Fnac ?', a: 'Les guides 2026 citent 39,90 € à 49,99 € HT par mois. Le montant exact figure dans votre contrat : ajustez le champ « Abonnement mensuel » si nécessaire.' }, { q: 'Y a-t-il des frais par commande ?', a: 'Plusieurs guides mentionnent environ 0,99 € de frais de paiement par commande et 2 € de frais de traitement par retour. Ces montants sont modifiables dans le calculateur.' }, { q: 'Quand suis-je payé ?', a: 'Le versement intervient 11 jours après confirmation de livraison pour les vendeurs établis, jusqu’à 30 jours pour les nouveaux vendeurs.' }] },
      it: { title: 'Calcolatore commissioni Fnac Marketplace 2026 – costi venditore e margine', desc: 'Calcola le commissioni Fnac Marketplace: 6–16 % per categoria e condizione (nuovo, ricondizionato, usato), abbonamento mensile, costo per ordine, accredito e profitto netto.', h1: 'Calcolatore commissioni Fnac Marketplace (2026)', intro: 'Su Fnac Marketplace (Francia) la commissione dipende da categoria e condizione del prodotto: dal 6 % (TV, hard disk nuovi) al 16 % (accessori ricondizionati o usati). Si aggiungono un abbonamento mensile professionale e un costo fisso per ordine. Il calcolatore combina tutto e mostra commissione, accredito e profitto netto per vendita.',
        cats: ['Computer & tablet – 7 / 8 / 10 %', 'Hard disk, TV, videoproiettori – 6 / 10 / 10 %', 'Grandi elettrodomestici – 6,5 / 10 / 10 %', 'Foto & obiettivi – 7 / 10 / 10 %', 'Piccoli elettrodomestici – 8 / 10 / 10 %', 'Smartphone – 8 / 8 / 10 %', 'Audio, DJ – 8 / 10 / 10 %', 'Accessori gaming – 13 / 16 / 16 %', 'Accessori hi-tech – 12 / 16 / 16 %', 'Giocattoli, giochi, salute – 12 / 16 / 16 %', 'Libri – 12 / 15 / 15 %', 'Sport & valigeria – 14 / 15 / 15 %', 'Biancheria per la casa – 15 %', 'Mobili – 15 %'],
        cond: ['Nuovo', 'Ricondizionato', 'Usato'], f: { cond: 'Condizione', sub: 'Abbonamento mensile (netto)', perOrder: 'Costo fisso per ordine' }, o: { new: 'Nuovo', refurb: 'Ricondizionato', used: 'Usato' }, fee: { commission: 'Commissione Fnac', perOrder: 'Costo fisso per ordine', sub: 'Abbonamento / ordine' },
        notes: ['Aliquota per categoria e condizione: es. computer & tablet 7 % (nuovo) / 8 % (ricondizionato) / 10 % (usato), libri 12 / 15 / 15 %, mobili 15 %.', 'Abbonamento professionale: da €39,90 a €49,99 netto al mese secondo le fonti 2026 – verifica nel tuo account e modifica il campo.', 'Diverse guide indicano circa €0,99 di costi di pagamento per ordine e €2 per reso; modifica se il tuo contratto è diverso.', 'Base della commissione: prezzo IVA inclusa + spedizione secondo le nostre fonti; pagamento delle vendite 11–30 giorni dopo la consegna.'],
        faq: [{ q: 'Qual è la commissione di Fnac Marketplace?', a: 'Dal 6 % al 16 % a seconda di categoria e condizione. Esempi: laptop 7 % nuovo, 8 % ricondizionato, 10 % usato; libri 12 % nuovo, 15 % usato; mobili e biancheria 15 %.' }, { q: 'Quanto costa l’abbonamento venditore Fnac?', a: 'Le guide 2026 indicano da €39,90 a €49,99 netto al mese. L’importo esatto è nel tuo contratto: modifica il campo “abbonamento mensile” se necessario.' }, { q: 'Ci sono costi per ordine?', a: 'Diverse guide citano circa €0,99 di costi di pagamento per ordine e €2 di gestione per reso. Entrambi sono modificabili nel calcolatore.' }, { q: 'Quando vengo pagato?', a: '11 giorni dopo la consegna confermata per i venditori consolidati, fino a 30 giorni per i nuovi venditori.' }] },
      es: { title: 'Calculadora de comisiones Fnac Marketplace 2026 – tarifas de vendedor y margen', desc: 'Calcula las tarifas de Fnac Marketplace: comisión del 6–16 % por categoría y estado (nuevo, reacondicionado, usado), suscripción mensual, tarifa por pedido, importe recibido y beneficio neto.', h1: 'Calculadora de comisiones Fnac Marketplace (2026)', intro: 'En Fnac Marketplace (Francia) la comisión depende de la categoría y del estado del producto: del 6 % (TV, discos duros nuevos) al 16 % (accesorios reacondicionados o usados). Se añaden una suscripción mensual profesional y una tarifa fija por pedido. La calculadora lo combina todo y muestra comisión, importe recibido y beneficio neto por venta.',
        cats: ['Ordenadores y tablets – 7 / 8 / 10 %', 'Discos duros, TV, proyectores – 6 / 10 / 10 %', 'Grandes electrodomésticos – 6,5 / 10 / 10 %', 'Cámaras y objetivos – 7 / 10 / 10 %', 'Pequeños electrodomésticos – 8 / 10 / 10 %', 'Smartphones – 8 / 8 / 10 %', 'Audio, DJ – 8 / 10 / 10 %', 'Accesorios gaming – 13 / 16 / 16 %', 'Accesorios tecnológicos – 12 / 16 / 16 %', 'Juguetes, juegos, salud – 12 / 16 / 16 %', 'Libros – 12 / 15 / 15 %', 'Deporte y equipaje – 14 / 15 / 15 %', 'Textil hogar – 15 %', 'Muebles – 15 %'],
        cond: ['Nuevo', 'Reacondicionado', 'Usado'], f: { cond: 'Estado', sub: 'Suscripción mensual (neta)', perOrder: 'Tarifa fija por pedido' }, o: { new: 'Nuevo', refurb: 'Reacondicionado', used: 'Usado' }, fee: { commission: 'Comisión Fnac', perOrder: 'Tarifa fija por pedido', sub: 'Suscripción / pedido' },
        notes: ['Tarifa según categoría y estado: p. ej. ordenadores y tablets 7 % (nuevo) / 8 % (reacondicionado) / 10 % (usado), libros 12 / 15 / 15 %, muebles 15 %.', 'Suscripción profesional: de 39,90 a 49,99 € netos al mes según las fuentes de 2026; compruébalo en tu cuenta y ajusta el campo.', 'Varias guías indican unos 0,99 € de gastos de pago por pedido y 2 € por devolución; modifícalo si tu contrato es distinto.', 'Base de la comisión: precio con IVA + envío según nuestras fuentes; el pago de las ventas llega entre 11 y 30 días tras la entrega.'],
        faq: [{ q: '¿Cuál es la comisión de Fnac Marketplace?', a: 'Del 6 % al 16 % según categoría y estado. Ejemplos: portátiles 7 % nuevo, 8 % reacondicionado, 10 % usado; libros 12 % nuevo, 15 % usado; muebles y textil hogar 15 %.' }, { q: '¿Cuánto cuesta la suscripción de vendedor de Fnac?', a: 'Las guías de 2026 citan de 39,90 a 49,99 € netos al mes. El importe exacto está en tu contrato: ajusta el campo “suscripción mensual” si hace falta.' }, { q: '¿Hay tarifas por pedido?', a: 'Varias guías mencionan unos 0,99 € de gastos de pago por pedido y 2 € de gestión por devolución. Ambos se pueden editar en la calculadora.' }, { q: '¿Cuándo cobro?', a: 'El pago se realiza 11 días después de la entrega confirmada para vendedores consolidados y hasta 30 días para vendedores nuevos.' }] },
      nl: { title: 'Fnac Marketplace commissie berekenen 2026 – verkoperskosten en marge', desc: 'Bereken je Fnac Marketplace-kosten: 6–16 % commissie per categorie en staat (nieuw, refurbished, tweedehands), maandabonnement, kosten per bestelling, uitbetaling en nettowinst.', h1: 'Fnac Marketplace commissie berekenen (2026)', intro: 'Op Fnac Marketplace (Frankrijk) hangt de commissie af van categorie en staat van het product: van 6 % (nieuwe tv’s, harde schijven) tot 16 % (refurbished of tweedehands accessoires). Daar komen een professioneel maandabonnement en vaste kosten per bestelling bij. De calculator combineert alles en toont commissie, uitbetaling en nettowinst per verkoop.',
        cats: ['Computers & tablets – 7 / 8 / 10 %', 'Harde schijven, tv, beamers – 6 / 10 / 10 %', 'Grote apparaten – 6,5 / 10 / 10 %', 'Camera’s & objectieven – 7 / 10 / 10 %', 'Kleine apparaten – 8 / 10 / 10 %', 'Smartphones – 8 / 8 / 10 %', 'Audio, dj – 8 / 10 / 10 %', 'Gaming-accessoires – 13 / 16 / 16 %', 'Tech-accessoires – 12 / 16 / 16 %', 'Speelgoed, spellen, gezondheid – 12 / 16 / 16 %', 'Boeken – 12 / 15 / 15 %', 'Sport & bagage – 14 / 15 / 15 %', 'Huishoudtextiel – 15 %', 'Meubels – 15 %'],
        cond: ['Nieuw', 'Refurbished', 'Tweedehands'], f: { cond: 'Staat', sub: 'Maandabonnement (netto)', perOrder: 'Vaste kosten per bestelling' }, o: { new: 'Nieuw', refurb: 'Refurbished', used: 'Tweedehands' }, fee: { commission: 'Fnac-commissie', perOrder: 'Vaste kosten per bestelling', sub: 'Abonnement / bestelling' },
        notes: ['Tarief per categorie en staat: bijv. computers & tablets 7 % (nieuw) / 8 % (refurbished) / 10 % (tweedehands), boeken 12 / 15 / 15 %, meubels 15 %.', 'Professioneel abonnement: € 39,90 tot € 49,99 netto per maand volgens bronnen uit 2026 – controleer je verkoopaccount en pas het veld aan.', 'Meerdere gidsen noemen ongeveer € 0,99 betalingskosten per bestelling en € 2 per retour; wijzig dit als je contract afwijkt.', 'Commissiebasis: prijs incl. btw + verzending volgens onze bronnen; uitbetaling 11 tot 30 dagen na levering.'],
        faq: [{ q: 'Hoe hoog is de commissie van Fnac Marketplace?', a: 'Van 6 % tot 16 %, afhankelijk van categorie en staat. Voorbeelden: laptops 7 % nieuw, 8 % refurbished, 10 % tweedehands; boeken 12 % nieuw, 15 % tweedehands; meubels en huishoudtextiel 15 %.' }, { q: 'Wat kost het Fnac-verkopersabonnement?', a: 'Gidsen uit 2026 noemen € 39,90 tot € 49,99 netto per maand. Het exacte bedrag staat in je contract: pas het veld “maandabonnement” zo nodig aan.' }, { q: 'Zijn er kosten per bestelling?', a: 'Meerdere gidsen noemen ongeveer € 0,99 betalingskosten per bestelling en € 2 verwerkingskosten per retour. Beide zijn aanpasbaar in de calculator.' }, { q: 'Wanneer word ik uitbetaald?', a: '11 dagen na bevestigde levering voor gevestigde verkopers, tot 30 dagen voor nieuwe verkopers.' }] },
      ja: { title: 'Fnac Marketplace 手数料計算ツール 2026｜出品者手数料と利益', desc: 'フランスのFnac Marketplaceの手数料を計算：カテゴリ×状態（新品・整備済み・中古）別6〜16%、月額出店料、注文ごとの固定費、入金額、純利益。', h1: 'Fnac Marketplace 手数料計算ツール（2026年版）', intro: 'Fnac Marketplace（フランス）の手数料はカテゴリと商品状態で決まります：6%（新品テレビ・HDD）から16%（整備済み・中古のアクセサリー）まで。これに月額出店料と注文ごとの固定費が加わります。すべてを合算し、販売1件あたりの手数料・入金額・純利益を表示します。',
        cats: ['PC・タブレット – 7 / 8 / 10%', 'HDD・テレビ・プロジェクター – 6 / 10 / 10%', '大型家電 – 6.5 / 10 / 10%', 'カメラ・レンズ – 7 / 10 / 10%', '小型家電 – 8 / 10 / 10%', 'スマートフォン – 8 / 8 / 10%', 'オーディオ・DJ – 8 / 10 / 10%', 'ゲーム周辺機器 – 13 / 16 / 16%', 'デジタル小物 – 12 / 16 / 16%', '玩具・ゲーム・ヘルスケア – 12 / 16 / 16%', '書籍 – 12 / 15 / 15%', 'スポーツ・バッグ – 14 / 15 / 15%', 'ホームテキスタイル – 15%', '家具 – 15%'],
        cond: ['新品', '整備済み', '中古'], f: { cond: '状態', sub: '月額出店料（税別）', perOrder: '注文ごとの固定費' }, o: { new: '新品', refurb: '整備済み', used: '中古' }, fee: { commission: 'Fnac手数料', perOrder: '注文ごとの固定費', sub: '月額出店料（按分）' },
        notes: ['料率はカテゴリ×状態：例 PC・タブレット 7%（新品）/ 8%（整備済み）/ 10%（中古）、書籍 12 / 15 / 15%、家具 15%。', '月額出店料：2026年の情報源により€39.90〜€49.99（税別）。管理画面で確認し、欄を調整してください。', '複数のガイドが注文ごと約€0.99の決済手数料と返品ごと€2を報告。契約が異なれば変更してください。', '手数料の対象は税込価格＋送料（当サイト調べ）。売上の入金は配達後11〜30日。'],
        faq: [{ q: 'Fnac Marketplaceの手数料は？', a: 'カテゴリと状態により6〜16%。例：ノートPC 新品7%・整備済み8%・中古10%、書籍 新品12%・中古15%、家具・ホームテキスタイル15%。' }, { q: '月額出店料はいくら？', a: '2026年のガイドでは€39.90〜€49.99（税別）。正確な金額は契約書に記載。必要に応じて「月額出店料」欄を修正してください。' }, { q: '注文ごとの費用はありますか？', a: '複数のガイドが注文ごと約€0.99の決済手数料、返品ごと€2の処理費を挙げています。どちらも編集可能です。' }, { q: '入金はいつ？', a: '既存出品者は配達確認後11日、新規出品者は最大30日後です。' }] },
      ko: { title: 'Fnac Marketplace 수수료 계산기 2026 | 판매자 수수료·마진', desc: '프랑스 Fnac Marketplace 수수료 계산: 카테고리×상태(새상품·리퍼·중고)별 6~16%, 월 구독료, 주문당 고정비, 정산금·순이익.', h1: 'Fnac Marketplace 수수료 계산기 (2026년)', intro: '프랑스 Fnac Marketplace의 수수료는 카테고리와 상품 상태에 따라 6%(새 TV·하드디스크)에서 16%(리퍼·중고 액세서리)까지 다릅니다. 여기에 전문 판매자 월 구독료와 주문당 고정비가 더해집니다. 계산기가 전부 합산해 판매 1건당 수수료·정산금·순이익을 보여줍니다.',
        cats: ['컴퓨터·태블릿 – 7 / 8 / 10%', '하드디스크·TV·프로젝터 – 6 / 10 / 10%', '대형가전 – 6.5 / 10 / 10%', '카메라·렌즈 – 7 / 10 / 10%', '소형가전 – 8 / 10 / 10%', '스마트폰 – 8 / 8 / 10%', '오디오·DJ – 8 / 10 / 10%', '게이밍 액세서리 – 13 / 16 / 16%', '테크 액세서리 – 12 / 16 / 16%', '완구·게임·헬스 – 12 / 16 / 16%', '도서 – 12 / 15 / 15%', '스포츠·여행가방 – 14 / 15 / 15%', '홈 텍스타일 – 15%', '가구 – 15%'],
        cond: ['새 상품', '리퍼', '중고'], f: { cond: '상품 상태', sub: '월 구독료(부가세 별도)', perOrder: '주문당 고정비' }, o: { new: '새 상품', refurb: '리퍼', used: '중고' }, fee: { commission: 'Fnac 수수료', perOrder: '주문당 고정비', sub: '구독료 (주문당 배분)' },
        notes: ['요율은 카테고리×상태: 예) 컴퓨터·태블릿 7%(새상품) / 8%(리퍼) / 10%(중고), 도서 12 / 15 / 15%, 가구 15%.', '전문 판매자 구독료: 2026년 자료에 따라 월 39.90~49.99€(부가세 별도). 판매자 계정에서 확인 후 수정하세요.', '여러 가이드가 주문당 약 0.99€ 결제수수료와 반품당 2€를 보고. 계약이 다르면 변경.', '수수료 기준: 부가세 포함가 + 배송비(당사 조사 기준). 정산은 배송 후 11~30일.'],
        faq: [{ q: 'Fnac Marketplace 수수료는 얼마인가요?', a: '카테고리와 상태에 따라 6~16%. 예: 노트북 새상품 7%·리퍼 8%·중고 10%, 도서 새상품 12%·중고 15%, 가구·홈 텍스타일 15%.' }, { q: 'Fnac 판매자 구독료는?', a: '2026년 가이드 기준 월 39.90~49.99€(부가세 별도). 정확한 금액은 계약서에 있으니 “월 구독료” 칸을 필요 시 수정하세요.' }, { q: '주문당 수수료가 있나요?', a: '여러 가이드가 주문당 약 0.99€ 결제수수료와 반품당 2€ 처리비를 언급합니다. 둘 다 계산기에서 수정 가능합니다.' }, { q: '정산은 언제 되나요?', a: '기존 판매자는 배송 확인 후 11일, 신규 판매자는 최대 30일 후입니다.' }] }
    }
  });
})(typeof window !== 'undefined' ? window : global);
