(function (root) {
  var SF = root.SF, F = SF.F, n = SF.n;
  SF.add({
    id: 'qoo10-jp', currency: 'JPY', flag: '🇯🇵', platform: 'Qoo10 Japan', region: 'JP', countries: ['JP'], names: {ja: 'Qoo10'},
    slug: { en: 'qoo10-japan-fee-calculator', de: 'qoo10-japan-gebuehrenrechner', fr: 'qoo10-japon-calculateur-commission', it: 'qoo10-giappone-calcolo-commissioni', es: 'qoo10-japon-calculadora-comisiones', nl: 'qoo10-japan-commissie-berekenen', ja: 'qoo10-fee-calculator', ko: 'qoo10-japan-fee-calculator' },
    fields: [F.price(3980), F.shipping(0), F.cost(1800), F.shipCost(600),
      F.cat(['10', '10', '10', '10', '10', '10', '9', '8', '8', '8', '8', '6', '6', '6', '6', '10'], '10'), F.commission(10),
      { k: 'extraPct', l: 'extraPct', t: 'sel', d: '0', o: [{ l: 'none', v: '0' }, { l: 'mega', v: '1' }, { l: 'mega2', v: '1.5' }, { l: 'preorder', v: '2' }] },
      F.vat(10), { k: 'wo', l: 'wo', t: 'num', u: '', d: 20, step: 1 }, F.other(), F.target()],
    fees: function (v) {
      var base = n(v.price) + n(v.shipping);
      var com = base * (n(v.commission) + n(v.extraPct)) / 100;
      return [{ k: 'commission', a: com }, { k: 'vatOnFees', a: com * n(v.vat) / 100 }, { k: 'withdraw', a: 150 / Math.max(1, n(v.wo)) }, { k: 'otherCost', a: base * n(v.other) / 100 }];
    },
    sources: [{ n: 'Finner：Qoo10の手数料を徹底解説（2026）', u: 'https://finner.co.jp/media/qoo10-fees-complete-guide/' }, { n: 'ECの相談室：Qoo10出店の手数料', u: 'https://bxo.co.jp/magazine/5044' }, { n: 'Qoo10 出店案内（公式）', u: 'https://www.qoo10.jp/gmkt.inc/Company/QSM.aspx' }],
    s: {
      en: { title: 'Qoo10 Japan Fee Calculator 2026 – Commission, Tax and Profit', desc: 'Qoo10 Japan seller fees by category (6–10 %), 10 % consumption tax on the fee, Mega Sale surcharge, withdrawal fee, payout, net profit and break-even price – free.', h1: 'Qoo10 Japan Fee Calculator (2026)', intro: 'Qoo10 Japan has no setup or monthly fee: you only pay a category commission of 6–10 % on product price + options + shipping when an item sells. 10 % consumption tax is added on the commission, and Mega Sale participation adds 1 %. Pick a category and the rate is prefilled; the calculator shows payout, net profit and break-even price.',
        cats: ['Women’s fashion – 10 %', 'Men’s fashion – 10 %', 'Beauty & cosmetics – 10 %', 'Beauty & health devices, e-cigarettes – 10 %', 'Sports & outdoor – 10 %', 'Food (general) – 10 %', 'Drugstore – 9 %', 'Kitchen, home & seasonal appliances – 8 %', 'PC & peripherals – 8 %', 'Games & cameras – 8 %', 'Bicycles – 8 %', 'Golf – 6 %', 'Beer – 6 %', 'Musical instruments – 6 %', 'CD, DVD, tickets – 6 %', 'Other – 10 %'],
        f: { extraPct: 'Additional fee', wo: 'Orders per withdrawal (¥150 fee spread)' }, o: { none: 'None', mega: 'Mega Sale (+1 %)', mega2: 'Mega Sale + Qoo10-funded discount (+1.5 %)', preorder: 'Pre-order / delayed shipping (+2 %)' }, fee: { commission: 'Sales commission', withdraw: 'Withdrawal fee (spread)' },
        notes: ['Commission = (product price + option price + shipping) × category rate (6–10 %).', '10 % consumption tax is charged on the commission (deductible for taxable businesses).', 'Mega Sale +1 %, Qoo10-funded discount +0.5 %, pre-order / delayed shipping +2 %.', 'No setup or monthly fee. Withdrawal fee ¥150 per payout.'],
        faq: [{ q: 'What is the Qoo10 Japan sales commission?', a: '6–10 % by category. Examples: women’s/men’s fashion, cosmetics and food 10 %, drugstore 9 %, appliances, PCs and games 8 %, golf, instruments, CD/DVD and beer 6 %. It applies to product price + options + shipping.' }, { q: 'Is tax charged on the commission?', a: 'Yes, 10 % consumption tax is added on the commission. Taxable businesses deduct it; tax-exempt sellers bear it as a cost.' }, { q: 'Are there monthly or setup fees?', a: 'No. Setup and monthly fees are ¥0; you only pay when an item sells. A ¥150 fee applies per withdrawal of your sales balance.' }, { q: 'Does Mega Sale raise the commission?', a: 'Participating adds +1 %, and joining the Qoo10-funded discount adds another +0.5 %. New sellers get up to 1 point off during Mega Sale.' }] },
      de: { title: 'Qoo10 Japan Gebührenrechner 2026 – Provision, Steuer und Gewinn', desc: 'Qoo10 Japan Händlergebühren je Kategorie (6–10 %), 10 % Verbrauchssteuer auf die Gebühr, Mega-Sale-Zuschlag, Auszahlungsgebühr, Auszahlung, Nettogewinn und Break-even-Preis – kostenlos.', h1: 'Qoo10 Japan Gebührenrechner (2026)', intro: 'Qoo10 Japan hat keine Einrichtungs- oder Monatsgebühr: Du zahlst nur eine Kategorieprovision von 6–10 % auf Produktpreis + Optionen + Versand, wenn ein Artikel verkauft wird. Auf die Provision kommen 10 % Verbrauchssteuer, die Mega-Sale-Teilnahme kostet 1 % extra. Kategorie wählen, Satz wird vorausgefüllt; der Rechner zeigt Auszahlung, Nettogewinn und Break-even-Preis.',
        cats: ['Damenmode – 10 %', 'Herrenmode – 10 %', 'Beauty & Kosmetik – 10 %', 'Beauty- & Gesundheitsgeräte, E-Zigaretten – 10 %', 'Sport & Outdoor – 10 %', 'Lebensmittel (allgemein) – 10 %', 'Drogerie – 9 %', 'Küchen-, Haushalts- & Saisongeräte – 8 %', 'PC & Zubehör – 8 %', 'Games & Kameras – 8 %', 'Fahrräder – 8 %', 'Golf – 6 %', 'Bier – 6 %', 'Musikinstrumente – 6 %', 'CD, DVD, Tickets – 6 %', 'Sonstiges – 10 %'],
        f: { extraPct: 'Zusatzgebühr', wo: 'Bestellungen pro Auszahlung (¥150 umgelegt)' }, o: { none: 'Keine', mega: 'Mega Sale (+1 %)', mega2: 'Mega Sale + Qoo10-finanzierter Rabatt (+1,5 %)', preorder: 'Vorbestellung / verzögerter Versand (+2 %)' }, fee: { commission: 'Verkaufsprovision', withdraw: 'Auszahlungsgebühr (umgelegt)' },
        notes: ['Provision = (Produktpreis + Optionspreis + Versand) × Kategoriesatz (6–10 %).', 'Auf die Provision kommen 10 % Verbrauchssteuer (für steuerpflichtige Unternehmen abziehbar).', 'Mega Sale +1 %, Qoo10-finanzierter Rabatt +0,5 %, Vorbestellung / verzögerter Versand +2 %.', 'Keine Einrichtungs- oder Monatsgebühr. Auszahlungsgebühr ¥150 pro Auszahlung.'],
        faq: [{ q: 'Wie hoch ist die Qoo10-Japan-Provision?', a: '6–10 % je Kategorie. Beispiele: Damen-/Herrenmode, Kosmetik und Lebensmittel 10 %, Drogerie 9 %, Geräte, PCs und Games 8 %, Golf, Instrumente, CD/DVD und Bier 6 %. Basis ist Produktpreis + Optionen + Versand.' }, { q: 'Kommt Steuer auf die Provision?', a: 'Ja, 10 % Verbrauchssteuer auf die Provision. Steuerpflichtige Unternehmen ziehen sie ab; steuerbefreite Händler tragen sie als Kosten.' }, { q: 'Gibt es Monats- oder Einrichtungsgebühren?', a: 'Nein. Beides ¥0; du zahlst nur bei Verkauf. Pro Auszahlung des Guthabens fallen ¥150 an.' }, { q: 'Erhöht der Mega Sale die Provision?', a: 'Teilnahme +1 %, zusätzlich Qoo10-finanzierter Rabatt +0,5 %. Neue Händler erhalten im Mega Sale bis zu 1 Punkt Nachlass.' }] },
      fr: { title: 'Calculateur de commission Qoo10 Japon 2026 – commission, taxe et bénéfice', desc: 'Frais vendeur Qoo10 Japon par catégorie (6–10 %), taxe de 10 % sur la commission, supplément Mega Sale, frais de retrait, montant reversé, bénéfice net et prix d’équilibre – gratuit.', h1: 'Calculateur de commission Qoo10 Japon (2026)', intro: 'Qoo10 Japon n’a ni frais d’installation ni abonnement : vous payez seulement une commission de 6 à 10 % selon la catégorie sur prix produit + options + port lorsqu’un article est vendu. Une taxe de consommation de 10 % s’ajoute sur la commission, et la participation au Mega Sale coûte 1 % de plus. Choisissez une catégorie, le taux se préremplit ; le calculateur affiche montant reversé, bénéfice net et prix d’équilibre.',
        cats: ['Mode femme – 10 %', 'Mode homme – 10 %', 'Beauté & cosmétiques – 10 %', 'Appareils beauté & santé, e-cigarettes – 10 %', 'Sport & outdoor – 10 %', 'Alimentaire (général) – 10 %', 'Parapharmacie – 9 %', 'Appareils cuisine, maison & saisonniers – 8 %', 'PC & périphériques – 8 %', 'Jeux & appareils photo – 8 %', 'Vélos – 8 %', 'Golf – 6 %', 'Bière – 6 %', 'Instruments de musique – 6 %', 'CD, DVD, billets – 6 %', 'Autre – 10 %'],
        f: { extraPct: 'Frais supplémentaires', wo: 'Commandes par retrait (¥150 répartis)' }, o: { none: 'Aucun', mega: 'Mega Sale (+1 %)', mega2: 'Mega Sale + remise financée par Qoo10 (+1,5 %)', preorder: 'Précommande / expédition différée (+2 %)' }, fee: { commission: 'Commission de vente', withdraw: 'Frais de retrait (répartis)' },
        notes: ['Commission = (prix produit + prix des options + port) × taux de la catégorie (6–10 %).', 'Une taxe de consommation de 10 % s’applique sur la commission (déductible pour les entreprises assujetties).', 'Mega Sale +1 %, remise financée par Qoo10 +0,5 %, précommande / expédition différée +2 %.', 'Pas de frais d’installation ni d’abonnement. Frais de retrait ¥150 par virement.'],
        faq: [{ q: 'Quelle est la commission de vente Qoo10 Japon ?', a: '6 à 10 % selon la catégorie. Exemples : mode femme/homme, cosmétiques et alimentaire 10 %, parapharmacie 9 %, appareils, PC et jeux 8 %, golf, instruments, CD/DVD et bière 6 %. Elle s’applique sur prix produit + options + port.' }, { q: 'Une taxe s’applique-t-elle sur la commission ?', a: 'Oui, 10 % de taxe de consommation s’ajoutent sur la commission. Les entreprises assujetties la déduisent ; les vendeurs exonérés la supportent comme un coût.' }, { q: 'Y a-t-il des frais mensuels ou d’installation ?', a: 'Non. Les deux sont à ¥0 ; vous ne payez qu’en cas de vente. Des frais de ¥150 s’appliquent à chaque retrait de votre solde.' }, { q: 'Le Mega Sale augmente-t-il la commission ?', a: 'La participation ajoute +1 %, et la remise financée par Qoo10 encore +0,5 %. Les nouveaux vendeurs bénéficient jusqu’à 1 point de réduction pendant le Mega Sale.' }] },
      it: { title: 'Calcolatore commissioni Qoo10 Giappone 2026 – commissione, imposta e profitto', desc: 'Commissioni venditore Qoo10 Giappone per categoria (6–10 %), imposta del 10 % sulla commissione, supplemento Mega Sale, costo di prelievo, accredito, profitto netto e prezzo di pareggio – gratis.', h1: 'Calcolatore commissioni Qoo10 Giappone (2026)', intro: 'Qoo10 Giappone non ha costi di attivazione né canone mensile: paghi solo una commissione del 6–10 % per categoria su prezzo prodotto + opzioni + spedizione quando un articolo viene venduto. Sulla commissione si aggiunge il 10 % di imposta sui consumi, e la partecipazione al Mega Sale costa l’1 % in più. Scegli la categoria e l’aliquota si precompila; il calcolatore mostra accredito, profitto netto e prezzo di pareggio.',
        cats: ['Moda donna – 10 %', 'Moda uomo – 10 %', 'Beauty & cosmetici – 10 %', 'Dispositivi beauty & salute, sigarette elettroniche – 10 %', 'Sport & outdoor – 10 %', 'Alimentari (generale) – 10 %', 'Parafarmacia – 9 %', 'Elettrodomestici cucina, casa & stagionali – 8 %', 'PC & periferiche – 8 %', 'Giochi & fotocamere – 8 %', 'Biciclette – 8 %', 'Golf – 6 %', 'Birra – 6 %', 'Strumenti musicali – 6 %', 'CD, DVD, biglietti – 6 %', 'Altro – 10 %'],
        f: { extraPct: 'Costo aggiuntivo', wo: 'Ordini per prelievo (¥150 ripartiti)' }, o: { none: 'Nessuno', mega: 'Mega Sale (+1 %)', mega2: 'Mega Sale + sconto finanziato da Qoo10 (+1,5 %)', preorder: 'Preordine / spedizione ritardata (+2 %)' }, fee: { commission: 'Commissione di vendita', withdraw: 'Costo di prelievo (ripartito)' },
        notes: ['Commissione = (prezzo prodotto + prezzo opzioni + spedizione) × aliquota della categoria (6–10 %).', 'Sulla commissione si applica il 10 % di imposta sui consumi (detraibile per le imprese soggette).', 'Mega Sale +1 %, sconto finanziato da Qoo10 +0,5 %, preordine / spedizione ritardata +2 %.', 'Nessun costo di attivazione o canone mensile. Costo di prelievo ¥150 per ogni prelievo.'],
        faq: [{ q: 'Qual è la commissione di vendita di Qoo10 Giappone?', a: '6–10 % per categoria. Esempi: moda donna/uomo, cosmetici e alimentari 10 %, parafarmacia 9 %, elettrodomestici, PC e giochi 8 %, golf, strumenti, CD/DVD e birra 6 %. Si applica a prezzo prodotto + opzioni + spedizione.' }, { q: 'C’è un’imposta sulla commissione?', a: 'Sì, il 10 % di imposta sui consumi si aggiunge sulla commissione. Le imprese soggette la detraggono; i venditori esenti la sostengono come costo.' }, { q: 'Ci sono canoni mensili o costi di attivazione?', a: 'No. Entrambi sono ¥0; paghi solo quando vendi. Ogni prelievo del saldo costa ¥150.' }, { q: 'Il Mega Sale aumenta la commissione?', a: 'Partecipare aggiunge +1 %, e aderire allo sconto finanziato da Qoo10 un ulteriore +0,5 %. I nuovi venditori ottengono fino a 1 punto di sconto durante il Mega Sale.' }] },
      es: { title: 'Calculadora de comisiones Qoo10 Japón 2026 – comisión, impuesto y beneficio', desc: 'Tarifas de vendedor de Qoo10 Japón por categoría (6–10 %), impuesto del 10 % sobre la comisión, recargo Mega Sale, tarifa de retirada, importe recibido, beneficio neto y precio de equilibrio – gratis.', h1: 'Calculadora de comisiones Qoo10 Japón (2026)', intro: 'Qoo10 Japón no tiene cuota de alta ni mensual: solo pagas una comisión por categoría del 6–10 % sobre precio del producto + opciones + envío cuando se vende un artículo. A la comisión se le añade un 10 % de impuesto al consumo, y participar en el Mega Sale cuesta un 1 % más. Elige una categoría y la tarifa se precarga; la calculadora muestra importe recibido, beneficio neto y precio de equilibrio.',
        cats: ['Moda mujer – 10 %', 'Moda hombre – 10 %', 'Belleza y cosmética – 10 %', 'Aparatos de belleza y salud, cigarrillos electrónicos – 10 %', 'Deporte y aire libre – 10 %', 'Alimentación (general) – 10 %', 'Parafarmacia – 9 %', 'Electrodomésticos de cocina, hogar y temporada – 8 %', 'PC y periféricos – 8 %', 'Videojuegos y cámaras – 8 %', 'Bicicletas – 8 %', 'Golf – 6 %', 'Cerveza – 6 %', 'Instrumentos musicales – 6 %', 'CD, DVD, entradas – 6 %', 'Otros – 10 %'],
        f: { extraPct: 'Tarifa adicional', wo: 'Pedidos por retirada (¥150 repartidos)' }, o: { none: 'Ninguna', mega: 'Mega Sale (+1 %)', mega2: 'Mega Sale + descuento financiado por Qoo10 (+1,5 %)', preorder: 'Preventa / envío diferido (+2 %)' }, fee: { commission: 'Comisión de venta', withdraw: 'Tarifa de retirada (repartida)' },
        notes: ['Comisión = (precio del producto + precio de opciones + envío) × tarifa de la categoría (6–10 %).', 'Sobre la comisión se cobra un 10 % de impuesto al consumo (deducible para empresas sujetas).', 'Mega Sale +1 %, descuento financiado por Qoo10 +0,5 %, preventa / envío diferido +2 %.', 'Sin cuota de alta ni mensual. Tarifa de retirada de ¥150 por cada retirada.'],
        faq: [{ q: '¿Cuál es la comisión de venta de Qoo10 Japón?', a: '6–10 % según categoría. Ejemplos: moda mujer/hombre, cosmética y alimentación 10 %, parafarmacia 9 %, electrodomésticos, PC y videojuegos 8 %, golf, instrumentos, CD/DVD y cerveza 6 %. Se aplica sobre precio del producto + opciones + envío.' }, { q: '¿Se cobra impuesto sobre la comisión?', a: 'Sí, se añade un 10 % de impuesto al consumo sobre la comisión. Las empresas sujetas lo deducen; los vendedores exentos lo asumen como coste.' }, { q: '¿Hay cuotas mensuales o de alta?', a: 'No. Ambas son ¥0; solo pagas cuando vendes. Cada retirada de saldo tiene una tarifa de ¥150.' }, { q: '¿El Mega Sale sube la comisión?', a: 'Participar añade +1 %, y sumarse al descuento financiado por Qoo10 otro +0,5 %. Los nuevos vendedores obtienen hasta 1 punto de descuento durante el Mega Sale.' }] },
      nl: { title: 'Qoo10 Japan commissie berekenen 2026 – commissie, belasting en winst', desc: 'Qoo10 Japan verkoperskosten per categorie (6–10 %), 10 % verbruiksbelasting over de commissie, Mega Sale-toeslag, opnamekosten, uitbetaling, nettowinst en break-evenprijs – gratis.', h1: 'Qoo10 Japan commissie berekenen (2026)', intro: 'Qoo10 Japan kent geen opstart- of maandkosten: je betaalt alleen een categoriecommissie van 6–10 % over productprijs + opties + verzending als een artikel verkocht wordt. Over de commissie komt 10 % verbruiksbelasting, en deelname aan de Mega Sale kost 1 % extra. Kies een categorie en het tarief wordt ingevuld; de calculator toont uitbetaling, nettowinst en break-evenprijs.',
        cats: ['Damesmode – 10 %', 'Herenmode – 10 %', 'Beauty & cosmetica – 10 %', 'Beauty- & gezondheidsapparaten, e-sigaretten – 10 %', 'Sport & outdoor – 10 %', 'Food (algemeen) – 10 %', 'Drogisterij – 9 %', 'Keuken-, huishoud- & seizoensapparaten – 8 %', 'Pc & randapparatuur – 8 %', 'Games & camera’s – 8 %', 'Fietsen – 8 %', 'Golf – 6 %', 'Bier – 6 %', 'Muziekinstrumenten – 6 %', 'Cd, dvd, tickets – 6 %', 'Overig – 10 %'],
        f: { extraPct: 'Extra kosten', wo: 'Bestellingen per opname (¥150 omgeslagen)' }, o: { none: 'Geen', mega: 'Mega Sale (+1 %)', mega2: 'Mega Sale + door Qoo10 betaalde korting (+1,5 %)', preorder: 'Pre-order / vertraagde verzending (+2 %)' }, fee: { commission: 'Verkoopcommissie', withdraw: 'Opnamekosten (omgeslagen)' },
        notes: ['Commissie = (productprijs + optieprijs + verzending) × categorietarief (6–10 %).', 'Over de commissie komt 10 % verbruiksbelasting (aftrekbaar voor belastingplichtige bedrijven).', 'Mega Sale +1 %, door Qoo10 betaalde korting +0,5 %, pre-order / vertraagde verzending +2 %.', 'Geen opstart- of maandkosten. Opnamekosten ¥150 per uitbetaling.'],
        faq: [{ q: 'Hoe hoog is de verkoopcommissie van Qoo10 Japan?', a: '6–10 % per categorie. Voorbeelden: dames-/herenmode, cosmetica en food 10 %, drogisterij 9 %, apparaten, pc’s en games 8 %, golf, instrumenten, cd/dvd en bier 6 %. Geldt over productprijs + opties + verzending.' }, { q: 'Wordt er belasting over de commissie gerekend?', a: 'Ja, 10 % verbruiksbelasting over de commissie. Belastingplichtige bedrijven trekken die af; vrijgestelde verkopers dragen die als kosten.' }, { q: 'Zijn er maand- of opstartkosten?', a: 'Nee. Beide zijn ¥0; je betaalt alleen bij verkoop. Per opname van je saldo betaal je ¥150.' }, { q: 'Verhoogt de Mega Sale de commissie?', a: 'Deelname is +1 %, en meedoen met de door Qoo10 betaalde korting nog eens +0,5 %. Nieuwe verkopers krijgen tijdens de Mega Sale tot 1 punt korting.' }] },
      ja: { title: 'Qoo10 手数料計算ツール 2026｜販売手数料・消費税・利益を自動計算', desc: 'Qoo10（日本）の販売手数料をカテゴリ別（6〜10%）に自動入力し、手数料の消費税、メガ割追加分、振込手数料、入金額、純利益、損益分岐価格を無料で計算。', h1: 'Qoo10 手数料計算ツール（2026年版）', intro: 'Qoo10は初期費用・月額固定費が0円で、売れたときだけ「商品価格＋オプション＋送料」に対してカテゴリ別6〜10%の販売手数料がかかります。手数料には消費税10%が別途加算され、メガ割参加時は+1%。カテゴリを選ぶだけで手数料率が自動入力され、入金額・純利益・損益分岐価格が表示されます。',
        cats: ['レディースファッション – 10%', 'メンズファッション – 10%', 'ビューティー・コスメ – 10%', '美容・健康家電・電子タバコ – 10%', 'スポーツ・アウトドア – 10%', '食品（一般） – 10%', 'ドラッグストア – 9%', 'キッチン・生活・季節家電 – 8%', 'PC・周辺機器 – 8%', 'ゲーム・カメラ – 8%', '自転車 – 8%', 'ゴルフ – 6%', 'お酒（ビール） – 6%', '楽器 – 6%', 'CD・DVD・チケット – 6%', 'その他 – 10%'],
        f: { extraPct: '追加手数料', wo: '1回の出金あたりの注文数（振込手数料150円の按分）' }, o: { none: 'なし', mega: 'メガ割参加（+1%）', mega2: 'メガ割＋Qoo10負担割引参加（+1.5%）', preorder: '予約販売・遅延発送（+2%）' }, fee: { commission: '販売手数料', withdraw: '振込手数料（按分）' },
        notes: ['販売手数料 ＝（商品価格＋オプション価格＋送料）× カテゴリ別料率（6〜10%）。', '手数料には消費税10%が別途かかります（課税事業者は仕入税額控除可）。', 'メガ割参加で+1%、Qoo10負担割引参加でさらに+0.5%、予約販売・遅延発送は+2%。', '初期費用・月額固定費は0円。出金時に振込手数料150円/回。'],
        faq: [{ q: 'Qoo10の販売手数料はいくらですか？', a: 'カテゴリ別に6〜10%です。例：レディース／メンズファッション、コスメ、食品は10%、ドラッグストア9%、家電・PC・ゲーム8%、ゴルフ・楽器・CD／DVD・ビールは6%。対象は商品価格＋オプション価格＋送料の合計です。' }, { q: '手数料に消費税はかかりますか？', a: 'はい、販売手数料に対して消費税10%が別途かかります。課税事業者なら仕入税額控除できるため実質負担はありませんが、免税事業者は費用になります。' }, { q: '月額費用や初期費用はありますか？', a: 'ありません。初期費用・月額固定費ともに0円で、売れたときだけ手数料が発生します。売上金の出金時に振込手数料150円がかかります。' }, { q: 'メガ割に参加すると手数料は上がりますか？', a: '参加すると+1%、Qoo10負担割引にも参加するとさらに+0.5%です。新規出店者はメガ割時に料率が最大1ポイント引き下げられる特典があります。' }] },
      ko: { title: 'Qoo10 일본 수수료 계산기 2026 | 판매수수료·소비세·순이익', desc: 'Qoo10 일본 카테고리별 판매수수료(6~10%), 수수료 소비세 10%, 메가할인 추가분, 출금 수수료를 반영해 정산금·순이익·손익분기 판매가를 무료 계산. 한국 셀러 일본 진출 필수 도구.', h1: 'Qoo10 일본 수수료 계산기 (2026년)', intro: 'Qoo10 일본은 입점비·월 고정비가 0원이고, 팔릴 때만 “상품가 + 옵션가 + 배송비”에 카테고리별 6~10% 판매수수료가 붙습니다. 수수료에 소비세 10%가 별도 가산되고, 메가할인 참여 시 +1%. 카테고리만 고르면 요율이 자동 입력되고 정산금·순이익·손익분기 판매가가 표시됩니다.',
        cats: ['여성 패션 – 10%', '남성 패션 – 10%', '뷰티·코스메틱 – 10%', '미용·건강가전·전자담배 – 10%', '스포츠·아웃도어 – 10%', '식품(일반) – 10%', '드러그스토어 – 9%', '주방·생활·계절가전 – 8%', 'PC·주변기기 – 8%', '게임·카메라 – 8%', '자전거 – 8%', '골프 – 6%', '맥주 – 6%', '악기 – 6%', 'CD·DVD·티켓 – 6%', '기타 – 10%'],
        f: { extraPct: '추가 수수료', wo: '출금 1회당 주문 수(출금 수수료 150엔 배분)' }, o: { none: '없음', mega: '메가할인 참여 (+1%)', mega2: '메가할인 + Qoo10 부담 할인 참여 (+1.5%)', preorder: '예약판매·지연발송 (+2%)' }, fee: { commission: '판매수수료', withdraw: '출금 수수료 (배분)' },
        notes: ['판매수수료 = (상품가 + 옵션가 + 배송비) × 카테고리 요율(6~10%).', '수수료에 소비세 10%가 별도(과세사업자는 매입세액공제 가능).', '메가할인 참여 +1%, Qoo10 부담 할인 참여 시 추가 +0.5%, 예약판매·지연발송 +2%.', '입점비·월 고정비 0원. 출금 시 회당 150엔 송금 수수료.'],
        faq: [{ q: 'Qoo10 일본 판매수수료는 얼마인가요?', a: '카테고리별 6~10%. 예: 여성/남성 패션·코스메틱·식품 10%, 드러그스토어 9%, 가전·PC·게임 8%, 골프·악기·CD/DVD·맥주 6%. 상품가 + 옵션가 + 배송비 합계가 기준입니다.' }, { q: '수수료에 소비세가 붙나요?', a: '네, 판매수수료에 소비세 10%가 별도로 붙습니다. 일본 과세사업자는 매입세액공제가 가능하지만 면세사업자·해외 셀러는 비용이 됩니다.' }, { q: '월 이용료나 입점비가 있나요?', a: '없습니다. 둘 다 0원이고 팔릴 때만 수수료가 발생합니다. 판매대금 출금 시 회당 150엔이 듭니다.' }, { q: '메가할인에 참여하면 수수료가 오르나요?', a: '참여 시 +1%, Qoo10 부담 할인까지 참여하면 추가 +0.5%. 신규 입점자는 메가할인 기간에 최대 1%p 인하 혜택이 있습니다.' }] }
    }
  });
})(typeof window !== 'undefined' ? window : global);
