(function (root) {
  var SF = root.SF, F = SF.F, n = SF.n;
  SF.add({
    id: 'rakuten-jp', currency: 'JPY', flag: '🇯🇵', platform: 'Rakuten Ichiba', region: 'JP', countries: ['JP'], names: {ja: '楽天市場',ko: '라쿠텐'}, primary: ['plan', 'tier', 'dev', 'sysfee'], rateNote: { key: 'sysfeeShort', lo: 2, hi: 7 },
    slug: { en: 'rakuten-ichiba-fee-calculator', de: 'rakuten-ichiba-gebuehrenrechner', fr: 'rakuten-ichiba-calculateur-commission', it: 'rakuten-ichiba-calcolo-commissioni', es: 'rakuten-ichiba-calculadora-comisiones', nl: 'rakuten-ichiba-commissie-berekenen', ja: 'rakuten-fee-calculator', ko: 'rakuten-fee-calculator' },
    fields: [F.price(4980), F.shipping(0), F.cost(2200), F.shipCost(700),
      { k: 'plan', l: 'plan', t: 'sel', d: 'g', o: [{ l: 'g', v: 'g' }, { l: 's', v: 's' }, { l: 'm', v: 'm' }] },
      { k: 'tier', l: 'tier', t: 'sel', d: '0', o: [{ l: 't0', v: '0' }, { l: 't1', v: '1' }, { l: 't2', v: '2' }, { l: 't3', v: '3' }, { l: 't4', v: '4' }] },
      { k: 'dev', l: 'dev', t: 'sel', d: '1', o: [{ l: 'mobile', v: '1' }, { l: 'pc', v: '0' }] },
      { k: 'sysfee', l: 'sysfee', t: 'num', u: '%', d: 7.0, step: 0.1 },
      { k: 'pay', l: 'pay', t: 'num', u: '%', d: 3.5, step: 0.1 },
      { k: 'points', l: 'points', t: 'num', u: '%', d: 1.0, step: 0.1 },
      { k: 'aff', l: 'aff', t: 'num', u: '%', d: 0, step: 0.1 },
      { k: 'monthly', l: 'monthly', t: 'num', u: 'cur', d: 28000, step: 1 },
      F.orders(150), F.other(), F.target()],
    derive: function (v, k) {
      if (k !== undefined && ['plan', 'tier', 'dev'].indexOf(k) < 0) return;
      var g = [[6.5, 7.0], [6.0, 6.5], [5.5, 6.0], [5.0, 5.5], [4.5, 5.0]], s = [[4.0, 4.5], [3.5, 4.0], [3.0, 3.5], [2.5, 3.0], [2.0, 2.5]];
      var row = (v.plan === 'g' ? g : s)[Math.min(4, n(v.tier))];
      v.sysfee = row[n(v.dev) ? 1 : 0];
      v.monthly = { g: 28000, s: 70000, m: 135000 }[v.plan] || 28000;
    },
    fees: function (v) {
      var base = n(v.price) + n(v.shipping), p = n(v.price);
      return [{ k: 'sysfee', a: base * n(v.sysfee) / 100 }, { k: 'pay', a: base * n(v.pay) / 100 }, { k: 'points', a: p * n(v.points) / 100 }, { k: 'safety', a: base * 0.001 }, { k: 'aff', a: p * n(v.aff) / 100 }, { k: 'monthly', a: n(v.monthly) / Math.max(1, n(v.orders)) }, { k: 'otherCost', a: base * n(v.other) / 100 }];
    },
    sources: [{ n: 'Finner：楽天市場の出店費用（2026）', u: 'https://finner.co.jp/media/rakuten-fee-simulation-by-sales/' }, { n: 'STOCKCREW：楽天市場の出店費用・手数料【2026年版】', u: 'https://stockcrew.co.jp/insights/rakuten-store-opening-fee-guide' }, { n: '楽天市場 出店案内（公式）', u: 'https://www.rakuten.co.jp/ec/' }],
    s: {
      en: { title: 'Rakuten Ichiba Fee Calculator 2026 – System Fee, Rakuten Pay, Monthly Plan per Order', desc: 'Rakuten Ichiba (Japan) fees per order: plan (Ganbare, Standard, Mega Shop), sales tier and PC/mobile system fee, Rakuten Pay, point subsidy, monthly plan fee spread per order, net profit.', h1: 'Rakuten Ichiba Fee Calculator (2026)', intro: 'Rakuten Ichiba costs have two layers: fixed monthly fees (plan fee ¥25,000–130,000 plus R-Messe) and sales-linked fees – system usage fee (2.0–7.0 %), Rakuten Pay (2.5–3.5 %), point subsidy (1.0 %+) and the 0.1 % safety system fee. Choose plan, monthly sales tier and orders per month; the calculator spreads fixed fees per order and shows the fee breakdown and net profit.',
        f: { plan: 'Store plan', tier: 'Monthly sales', dev: 'Order channel', sysfee: 'System usage fee %', pay: 'Rakuten Pay fee %', points: 'Point subsidy %', aff: 'Affiliate % (only on affiliate sales)', monthly: 'Monthly fixed fees (plan + R-Messe)' },
        o: { g: 'Ganbare! plan (¥25,000/month)', s: 'Standard plan (¥65,000/month)', m: 'Mega Shop plan (¥130,000/month)', t0: 'Up to ¥500k', t1: '¥500k–1M', t2: '¥1M–5M', t3: '¥5M–10M', t4: 'Over ¥10M', mobile: 'Mobile', pc: 'PC' },
        fee: { sysfee: 'System usage fee', pay: 'Rakuten Pay fee', points: 'Point subsidy', safety: 'Safety & convenience system fee (0.1 %)', aff: 'Affiliate fee', monthly: 'Monthly fixed fees (spread)' },
        notes: ['System usage fee varies by monthly sales and PC/mobile: Ganbare! 3.5–7.0 %, Standard/Mega Shop 2.0–4.5 % (ex tax). Tier boundaries are indicative.', 'Rakuten Pay fee is 2.5–3.5 % depending on monthly payment volume and average order value.', 'Point subsidy is normally 1.0 %; campaigns such as Shopping Marathon add more.', 'Monthly plan fees: Ganbare! ¥25,000, Standard ¥65,000, Mega Shop ¥130,000, R-Messe ¥3,000–5,000 (ex tax). The ¥60,000 initial registration fee is not included.'],
        faq: [{ q: 'What are the Rakuten Ichiba monthly plan fees?', a: 'Ganbare! ¥25,000, Standard ¥65,000, Mega Shop ¥130,000 per month (ex tax, paid annually or semi-annually), plus a ¥60,000 initial registration fee and R-Messe at ¥3,000–5,000 per month.' }, { q: 'How is the system usage fee determined?', a: 'By monthly sales tier and order channel. Ganbare!: PC 3.5–6.5 %, mobile 4.0–7.0 %; Standard/Mega Shop: PC 2.0–4.0 %, mobile 2.5–4.5 %. Rates fall as sales grow.' }, { q: 'Which other sales-linked fees apply?', a: 'Rakuten Pay 2.5–3.5 %, point subsidy 1.0 %+, safety & convenience system fee 0.1 %, and an effective 2.6–5.2 % on sales via affiliates. Advertising and logistics are extra.' }, { q: 'What do variable fees add up to?', a: 'Typically 8–15 % of sales. Fixed fees are divided by your order count, so fewer monthly orders mean a higher burden per order.' }] },
      de: { title: 'Rakuten Ichiba Gebührenrechner 2026 – Systemgebühr, Rakuten Pay, Monatsplan pro Bestellung', desc: 'Rakuten Ichiba (Japan) Gebühren pro Bestellung: Plan (Ganbare, Standard, Mega Shop), Umsatzstufe und PC/Mobil-Systemgebühr, Rakuten Pay, Punkte, Monatsgebühr pro Bestellung umgelegt, Nettogewinn.', h1: 'Rakuten Ichiba Gebührenrechner (2026)', intro: 'Die Kosten bei Rakuten Ichiba haben zwei Ebenen: feste Monatsgebühren (Plan ¥25.000–130.000 plus R-Messe) und umsatzabhängige Gebühren – Systemnutzungsgebühr (2,0–7,0 %), Rakuten Pay (2,5–3,5 %), Punktesubvention (1,0 %+) und 0,1 % Sicherheitsgebühr. Wähle Plan, Monatsumsatz und Bestellungen pro Monat; der Rechner legt die Fixkosten pro Bestellung um und zeigt Gebührenaufstellung und Nettogewinn.',
        f: { plan: 'Shop-Plan', tier: 'Monatsumsatz', dev: 'Bestellkanal', sysfee: 'Systemnutzungsgebühr %', pay: 'Rakuten-Pay-Gebühr %', points: 'Punktesubvention %', aff: 'Affiliate % (nur bei Affiliate-Verkäufen)', monthly: 'Feste Monatsgebühren (Plan + R-Messe)' },
        o: { g: 'Ganbare!-Plan (¥25.000/Monat)', s: 'Standard-Plan (¥65.000/Monat)', m: 'Mega-Shop-Plan (¥130.000/Monat)', t0: 'Bis ¥500.000', t1: '¥500.000–1 Mio.', t2: '¥1–5 Mio.', t3: '¥5–10 Mio.', t4: 'Über ¥10 Mio.', mobile: 'Mobil', pc: 'PC' },
        fee: { sysfee: 'Systemnutzungsgebühr', pay: 'Rakuten-Pay-Gebühr', points: 'Punktesubvention', safety: 'Sicherheits-Systemgebühr (0,1 %)', aff: 'Affiliate-Gebühr', monthly: 'Feste Monatsgebühren (umgelegt)' },
        notes: ['Systemnutzungsgebühr je nach Monatsumsatz und PC/Mobil: Ganbare! 3,5–7,0 %, Standard/Mega Shop 2,0–4,5 % (netto). Stufengrenzen sind Richtwerte.', 'Rakuten-Pay-Gebühr 2,5–3,5 % je nach monatlichem Zahlungsvolumen und Bestellwert.', 'Punktesubvention normal 1,0 %; Aktionen wie Shopping Marathon kommen dazu.', 'Monatsgebühren: Ganbare! ¥25.000, Standard ¥65.000, Mega Shop ¥130.000, R-Messe ¥3.000–5.000 (netto). Die einmalige Registrierungsgebühr von ¥60.000 ist nicht enthalten.'],
        faq: [{ q: 'Was kosten die Rakuten-Ichiba-Pläne monatlich?', a: 'Ganbare! ¥25.000, Standard ¥65.000, Mega Shop ¥130.000 pro Monat (netto, jährlich oder halbjährlich zahlbar), plus einmalig ¥60.000 Registrierung und R-Messe ¥3.000–5.000 pro Monat.' }, { q: 'Wie wird die Systemnutzungsgebühr bestimmt?', a: 'Nach Monatsumsatzstufe und Bestellkanal. Ganbare!: PC 3,5–6,5 %, Mobil 4,0–7,0 %; Standard/Mega Shop: PC 2,0–4,0 %, Mobil 2,5–4,5 %. Die Sätze sinken mit dem Umsatz.' }, { q: 'Welche weiteren umsatzabhängigen Gebühren gibt es?', a: 'Rakuten Pay 2,5–3,5 %, Punktesubvention 1,0 %+, Sicherheitsgebühr 0,1 % und effektiv 2,6–5,2 % auf Affiliate-Verkäufe. Werbung und Logistik kommen dazu.' }, { q: 'Wie hoch sind die variablen Gebühren insgesamt?', a: 'Typisch 8–15 % des Umsatzes. Fixkosten werden durch die Bestellzahl geteilt – je weniger Bestellungen pro Monat, desto höher die Belastung pro Bestellung.' }] },
      fr: { title: 'Calculateur de frais Rakuten Ichiba 2026 – frais système, Rakuten Pay, abonnement par commande', desc: 'Frais Rakuten Ichiba (Japon) par commande : formule (Ganbare, Standard, Mega Shop), palier de CA et frais système PC/mobile, Rakuten Pay, points, abonnement mensuel ramené par commande, bénéfice net.', h1: 'Calculateur de frais Rakuten Ichiba (2026)', intro: 'Les coûts Rakuten Ichiba ont deux niveaux : des frais mensuels fixes (formule ¥25 000–130 000 plus R-Messe) et des frais liés aux ventes – frais d’utilisation du système (2,0–7,0 %), Rakuten Pay (2,5–3,5 %), points (1,0 %+) et frais de sécurité 0,1 %. Choisissez formule, palier de CA mensuel et commandes par mois ; le calculateur répartit les frais fixes par commande et affiche le détail des frais et le bénéfice net.',
        f: { plan: 'Formule de boutique', tier: 'CA mensuel', dev: 'Canal de commande', sysfee: 'Frais d’utilisation du système %', pay: 'Frais Rakuten Pay %', points: 'Points offerts %', aff: 'Affiliation % (ventes affiliées seulement)', monthly: 'Frais fixes mensuels (formule + R-Messe)' },
        o: { g: 'Formule Ganbare! (¥25 000/mois)', s: 'Formule Standard (¥65 000/mois)', m: 'Formule Mega Shop (¥130 000/mois)', t0: 'Jusqu’à ¥500 000', t1: '¥500 000–1 M', t2: '¥1–5 M', t3: '¥5–10 M', t4: 'Plus de ¥10 M', mobile: 'Mobile', pc: 'PC' },
        fee: { sysfee: 'Frais d’utilisation du système', pay: 'Frais Rakuten Pay', points: 'Points offerts', safety: 'Frais système sécurité (0,1 %)', aff: 'Frais d’affiliation', monthly: 'Frais fixes mensuels (répartis)' },
        notes: ['Frais système selon le CA mensuel et PC/mobile : Ganbare! 3,5–7,0 %, Standard/Mega Shop 2,0–4,5 % (HT). Les paliers sont indicatifs.', 'Frais Rakuten Pay 2,5–3,5 % selon le volume mensuel encaissé et le panier moyen.', 'Points offerts normalement 1,0 % ; les opérations comme le Shopping Marathon s’ajoutent.', 'Frais mensuels : Ganbare! ¥25 000, Standard ¥65 000, Mega Shop ¥130 000, R-Messe ¥3 000–5 000 (HT). Les ¥60 000 de frais d’inscription initiaux ne sont pas inclus.'],
        faq: [{ q: 'Combien coûtent les formules Rakuten Ichiba par mois ?', a: 'Ganbare! ¥25 000, Standard ¥65 000, Mega Shop ¥130 000 par mois (HT, payables annuellement ou semestriellement), plus ¥60 000 de frais d’inscription et R-Messe à ¥3 000–5 000 par mois.' }, { q: 'Comment sont déterminés les frais système ?', a: 'Par palier de CA mensuel et canal de commande. Ganbare! : PC 3,5–6,5 %, mobile 4,0–7,0 % ; Standard/Mega Shop : PC 2,0–4,0 %, mobile 2,5–4,5 %. Les taux baissent avec le CA.' }, { q: 'Quels autres frais liés aux ventes s’appliquent ?', a: 'Rakuten Pay 2,5–3,5 %, points 1,0 %+, frais de sécurité 0,1 % et 2,6–5,2 % effectifs sur les ventes via affiliés. Publicité et logistique en plus.' }, { q: 'À combien s’élèvent les frais variables au total ?', a: 'Généralement 8 à 15 % du CA. Les frais fixes sont divisés par le nombre de commandes : moins de commandes par mois, plus la charge par commande est élevée.' }] },
      it: { title: 'Calcolatore commissioni Rakuten Ichiba 2026 – costo sistema, Rakuten Pay, canone per ordine', desc: 'Costi Rakuten Ichiba (Giappone) per ordine: piano (Ganbare, Standard, Mega Shop), fascia di vendite e costo sistema PC/mobile, Rakuten Pay, punti, canone mensile ripartito per ordine, profitto netto.', h1: 'Calcolatore commissioni Rakuten Ichiba (2026)', intro: 'I costi di Rakuten Ichiba hanno due livelli: canoni mensili fissi (piano ¥25.000–130.000 più R-Messe) e costi legati alle vendite – costo d’uso del sistema (2,0–7,0 %), Rakuten Pay (2,5–3,5 %), punti (1,0 %+) e 0,1 % di costo sicurezza. Scegli piano, fascia di vendite mensili e ordini al mese; il calcolatore ripartisce i costi fissi per ordine e mostra dettaglio e profitto netto.',
        f: { plan: 'Piano negozio', tier: 'Vendite mensili', dev: 'Canale ordine', sysfee: 'Costo d’uso del sistema %', pay: 'Costo Rakuten Pay %', points: 'Punti offerti %', aff: 'Affiliazione % (solo vendite affiliate)', monthly: 'Costi fissi mensili (piano + R-Messe)' },
        o: { g: 'Piano Ganbare! (¥25.000/mese)', s: 'Piano Standard (¥65.000/mese)', m: 'Piano Mega Shop (¥130.000/mese)', t0: 'Fino a ¥500.000', t1: '¥500.000–1 M', t2: '¥1–5 M', t3: '¥5–10 M', t4: 'Oltre ¥10 M', mobile: 'Mobile', pc: 'PC' },
        fee: { sysfee: 'Costo d’uso del sistema', pay: 'Costo Rakuten Pay', points: 'Punti offerti', safety: 'Costo sistema sicurezza (0,1 %)', aff: 'Costo affiliazione', monthly: 'Costi fissi mensili (ripartiti)' },
        notes: ['Costo sistema in base a vendite mensili e PC/mobile: Ganbare! 3,5–7,0 %, Standard/Mega Shop 2,0–4,5 % (netto). Le fasce sono indicative.', 'Costo Rakuten Pay 2,5–3,5 % in base al volume mensile incassato e allo scontrino medio.', 'Punti offerti normalmente 1,0 %; campagne come Shopping Marathon aggiungono altro.', 'Canoni mensili: Ganbare! ¥25.000, Standard ¥65.000, Mega Shop ¥130.000, R-Messe ¥3.000–5.000 (netto). I ¥60.000 di iscrizione iniziale non sono inclusi.'],
        faq: [{ q: 'Quanto costano i piani Rakuten Ichiba al mese?', a: 'Ganbare! ¥25.000, Standard ¥65.000, Mega Shop ¥130.000 al mese (netto, pagabili annualmente o semestralmente), più ¥60.000 di iscrizione iniziale e R-Messe a ¥3.000–5.000 al mese.' }, { q: 'Come si determina il costo d’uso del sistema?', a: 'In base alla fascia di vendite mensili e al canale. Ganbare!: PC 3,5–6,5 %, mobile 4,0–7,0 %; Standard/Mega Shop: PC 2,0–4,0 %, mobile 2,5–4,5 %. Le aliquote scendono al crescere delle vendite.' }, { q: 'Quali altri costi legati alle vendite ci sono?', a: 'Rakuten Pay 2,5–3,5 %, punti 1,0 %+, costo sicurezza 0,1 % e un effettivo 2,6–5,2 % sulle vendite tramite affiliati. Pubblicità e logistica a parte.' }, { q: 'A quanto ammontano i costi variabili in totale?', a: 'Di norma 8–15 % delle vendite. I costi fissi vengono divisi per il numero di ordini: meno ordini al mese, maggiore il peso per ordine.' }] },
      es: { title: 'Calculadora de tarifas Rakuten Ichiba 2026 – tarifa de sistema, Rakuten Pay, cuota por pedido', desc: 'Tarifas de Rakuten Ichiba (Japón) por pedido: plan (Ganbare, Standard, Mega Shop), tramo de ventas y tarifa de sistema PC/móvil, Rakuten Pay, puntos, cuota mensual repartida por pedido, beneficio neto.', h1: 'Calculadora de tarifas Rakuten Ichiba (2026)', intro: 'Los costes de Rakuten Ichiba tienen dos capas: cuotas mensuales fijas (plan ¥25.000–130.000 más R-Messe) y tarifas ligadas a las ventas: tarifa de uso del sistema (2,0–7,0 %), Rakuten Pay (2,5–3,5 %), puntos (1,0 %+) y 0,1 % de tarifa de seguridad. Elige plan, tramo de ventas mensuales y pedidos al mes; la calculadora reparte los costes fijos por pedido y muestra el desglose y el beneficio neto.',
        f: { plan: 'Plan de tienda', tier: 'Ventas mensuales', dev: 'Canal del pedido', sysfee: 'Tarifa de uso del sistema %', pay: 'Tarifa Rakuten Pay %', points: 'Puntos regalados %', aff: 'Afiliación % (solo ventas afiliadas)', monthly: 'Costes fijos mensuales (plan + R-Messe)' },
        o: { g: 'Plan Ganbare! (¥25.000/mes)', s: 'Plan Standard (¥65.000/mes)', m: 'Plan Mega Shop (¥130.000/mes)', t0: 'Hasta ¥500.000', t1: '¥500.000–1 M', t2: '¥1–5 M', t3: '¥5–10 M', t4: 'Más de ¥10 M', mobile: 'Móvil', pc: 'PC' },
        fee: { sysfee: 'Tarifa de uso del sistema', pay: 'Tarifa Rakuten Pay', points: 'Puntos regalados', safety: 'Tarifa de sistema de seguridad (0,1 %)', aff: 'Tarifa de afiliación', monthly: 'Costes fijos mensuales (repartidos)' },
        notes: ['Tarifa de sistema según ventas mensuales y PC/móvil: Ganbare! 3,5–7,0 %, Standard/Mega Shop 2,0–4,5 % (sin impuestos). Los tramos son orientativos.', 'Tarifa Rakuten Pay 2,5–3,5 % según el volumen mensual cobrado y el ticket medio.', 'Puntos regalados normalmente 1,0 %; campañas como el Shopping Marathon añaden más.', 'Cuotas mensuales: Ganbare! ¥25.000, Standard ¥65.000, Mega Shop ¥130.000, R-Messe ¥3.000–5.000 (sin impuestos). Los ¥60.000 de alta inicial no están incluidos.'],
        faq: [{ q: '¿Cuánto cuestan los planes de Rakuten Ichiba al mes?', a: 'Ganbare! ¥25.000, Standard ¥65.000, Mega Shop ¥130.000 al mes (sin impuestos, pagados anual o semestralmente), más ¥60.000 de alta inicial y R-Messe a ¥3.000–5.000 al mes.' }, { q: '¿Cómo se determina la tarifa de uso del sistema?', a: 'Por tramo de ventas mensuales y canal. Ganbare!: PC 3,5–6,5 %, móvil 4,0–7,0 %; Standard/Mega Shop: PC 2,0–4,0 %, móvil 2,5–4,5 %. Las tarifas bajan al crecer las ventas.' }, { q: '¿Qué otras tarifas ligadas a las ventas se aplican?', a: 'Rakuten Pay 2,5–3,5 %, puntos 1,0 %+, tarifa de seguridad 0,1 % y un 2,6–5,2 % efectivo en ventas vía afiliados. Publicidad y logística aparte.' }, { q: '¿A cuánto ascienden las tarifas variables en total?', a: 'Normalmente al 8–15 % de las ventas. Los costes fijos se dividen entre el número de pedidos: cuantos menos pedidos al mes, mayor la carga por pedido.' }] },
      nl: { title: 'Rakuten Ichiba commissie berekenen 2026 – systeemkosten, Rakuten Pay, maandplan per bestelling', desc: 'Rakuten Ichiba (Japan) kosten per bestelling: plan (Ganbare, Standard, Mega Shop), omzetschijf en pc/mobiel-systeemkosten, Rakuten Pay, punten, maandabonnement omgeslagen per bestelling, nettowinst.', h1: 'Rakuten Ichiba commissie berekenen (2026)', intro: 'De kosten van Rakuten Ichiba hebben twee lagen: vaste maandkosten (plan ¥25.000–130.000 plus R-Messe) en omzetgebonden kosten – systeemgebruikskosten (2,0–7,0 %), Rakuten Pay (2,5–3,5 %), puntensubsidie (1,0 %+) en 0,1 % veiligheidskosten. Kies plan, maandomzetschijf en bestellingen per maand; de calculator slaat de vaste kosten om per bestelling en toont het kostenoverzicht en de nettowinst.',
        f: { plan: 'Winkelplan', tier: 'Maandomzet', dev: 'Bestelkanaal', sysfee: 'Systeemgebruikskosten %', pay: 'Rakuten Pay-kosten %', points: 'Puntensubsidie %', aff: 'Affiliate % (alleen affiliate-verkopen)', monthly: 'Vaste maandkosten (plan + R-Messe)' },
        o: { g: 'Ganbare!-plan (¥25.000/maand)', s: 'Standard-plan (¥65.000/maand)', m: 'Mega Shop-plan (¥130.000/maand)', t0: 'Tot ¥500.000', t1: '¥500.000–1 mln', t2: '¥1–5 mln', t3: '¥5–10 mln', t4: 'Boven ¥10 mln', mobile: 'Mobiel', pc: 'Pc' },
        fee: { sysfee: 'Systeemgebruikskosten', pay: 'Rakuten Pay-kosten', points: 'Puntensubsidie', safety: 'Veiligheidssysteemkosten (0,1 %)', aff: 'Affiliate-kosten', monthly: 'Vaste maandkosten (omgeslagen)' },
        notes: ['Systeemkosten variëren met maandomzet en pc/mobiel: Ganbare! 3,5–7,0 %, Standard/Mega Shop 2,0–4,5 % (excl. belasting). Schijfgrenzen zijn indicatief.', 'Rakuten Pay-kosten 2,5–3,5 % afhankelijk van maandelijks betaalvolume en gemiddelde orderwaarde.', 'Puntensubsidie normaal 1,0 %; campagnes zoals de Shopping Marathon komen erbij.', 'Maandkosten: Ganbare! ¥25.000, Standard ¥65.000, Mega Shop ¥130.000, R-Messe ¥3.000–5.000 (excl. belasting). De eenmalige registratiekosten van ¥60.000 zijn niet meegenomen.'],
        faq: [{ q: 'Wat kosten de Rakuten Ichiba-plannen per maand?', a: 'Ganbare! ¥25.000, Standard ¥65.000, Mega Shop ¥130.000 per maand (excl. belasting, jaarlijks of halfjaarlijks te betalen), plus ¥60.000 eenmalige registratie en R-Messe ¥3.000–5.000 per maand.' }, { q: 'Hoe worden de systeemgebruikskosten bepaald?', a: 'Per maandomzetschijf en bestelkanaal. Ganbare!: pc 3,5–6,5 %, mobiel 4,0–7,0 %; Standard/Mega Shop: pc 2,0–4,0 %, mobiel 2,5–4,5 %. De tarieven dalen naarmate de omzet stijgt.' }, { q: 'Welke andere omzetgebonden kosten zijn er?', a: 'Rakuten Pay 2,5–3,5 %, puntensubsidie 1,0 %+, veiligheidskosten 0,1 % en effectief 2,6–5,2 % op verkopen via affiliates. Advertenties en logistiek komen erbij.' }, { q: 'Hoeveel zijn de variabele kosten in totaal?', a: 'Meestal 8–15 % van de omzet. Vaste kosten worden gedeeld door het aantal bestellingen: minder bestellingen per maand betekent een hogere last per bestelling.' }] },
      ja: { title: '楽天市場 手数料計算ツール 2026｜システム利用料・楽天ペイ・月額費用を1件あたりで計算', desc: '楽天市場の出店プラン（がんばれ！・スタンダード・メガショップ）、月間売上高、PC/モバイル別のシステム利用料、楽天ペイ、ポイント原資、月額出店料の按分まで含めて1注文あたりの手数料と純利益を計算。', h1: '楽天市場 手数料計算ツール（2026年版）', intro: '楽天市場の費用は、月額出店料（25,000〜130,000円）とR-Messe利用料の固定費に、売上連動のシステム利用料（2.0〜7.0%）、楽天ペイ利用料（2.5〜3.5%）、ポイント原資（1.0%〜）、安全性・利便性向上のためのシステム利用料（0.1%）が重なる二層構造です。プラン・月間売上高・注文数を選ぶと固定費を1注文あたりに按分し、手数料内訳と純利益を表示します。',
        f: { plan: '出店プラン', tier: '月間売上高', dev: '注文経路', sysfee: 'システム利用料 %', pay: '楽天ペイ利用料 %', points: 'ポイント原資 %', aff: 'アフィリエイト %（成果時のみ）', monthly: '月額固定費（出店料＋R-Messe）' },
        o: { g: 'がんばれ！プラン（月額25,000円）', s: 'スタンダードプラン（月額65,000円）', m: 'メガショッププラン（月額130,000円）', t0: '〜50万円', t1: '50万〜100万円', t2: '100万〜500万円', t3: '500万〜1,000万円', t4: '1,000万円〜', mobile: 'モバイル', pc: 'PC' },
        fee: { sysfee: 'システム利用料', pay: '楽天ペイ利用料', points: 'ポイント原資', safety: '安全性・利便性向上システム利用料（0.1%）', aff: 'アフィリエイト', monthly: '月額固定費（按分）' },
        notes: ['システム利用料は月間売上高とPC/モバイル別に変動：がんばれ！3.5〜7.0%、スタンダード／メガショップ2.0〜4.5%（税別）。売上区分の境界は目安です。', '楽天ペイ利用料は月間決済高・平均単価により2.5〜3.5%。', 'ポイント原資は通常1.0%。お買い物マラソン等のイベント時はさらに上乗せ。', '月額出店料：がんばれ！25,000円／スタンダード65,000円／メガショップ130,000円、R-Messe 3,000〜5,000円（税別）。初期登録費用60,000円は含みません。'],
        faq: [{ q: '楽天市場の月額出店料はいくらですか？', a: 'がんばれ！プラン25,000円、スタンダードプラン65,000円、メガショッププラン130,000円（いずれも税別、年一括または半年一括払い）。これに加えて初期登録費用60,000円、R-Messe利用料3,000〜5,000円/月がかかります。' }, { q: 'システム利用料はどう決まりますか？', a: '月間売上高の区分とPC／モバイルの注文経路で決まります。がんばれ！プランはPC 3.5〜6.5%、モバイル4.0〜7.0%、スタンダード／メガショップはPC 2.0〜4.0%、モバイル2.5〜4.5%。売上が増えるほど料率は下がります。' }, { q: 'その他の売上連動の費用は？', a: '楽天ペイ利用料2.5〜3.5%、ポイント原資1.0%〜、安全性・利便性向上のためのシステム利用料0.1%、アフィリエイト経由の売上には実質2.6〜5.2%の成果報酬。広告費・物流費は別途です。' }, { q: '変動費の合計はどのくらいですか？', a: '通常の運営で売上の8〜15%程度。固定費は注文数で割って1件あたりに換算しているため、月間注文数が少ないほど1件あたりの負担が大きくなります。' }] },
      ko: { title: '라쿠텐 (楽天市場) 수수료 계산기 2026 | 시스템이용료·라쿠텐페이·월정액 주문당 계산', desc: '라쿠텐 이치바 출점 플랜(간바레·스탠다드·메가샵), 월 매출 구간, PC/모바일별 시스템이용료, 라쿠텐페이, 포인트 원자, 월 출점료 배분까지 반영해 주문 1건당 수수료와 순이익을 계산.', h1: '라쿠텐 (楽天市場) 수수료 계산기 (2026년)', intro: '라쿠텐 이치바 비용은 두 층입니다: 월 출점료(25,000~130,000엔)와 R-Messe 이용료의 고정비, 그리고 매출 연동 시스템이용료(2.0~7.0%), 라쿠텐페이 이용료(2.5~3.5%), 포인트 원자(1.0%~), 안전성·편의성 향상 시스템이용료(0.1%). 플랜·월 매출·주문 수를 고르면 고정비를 주문당 배분해 수수료 내역과 순이익을 보여줍니다.',
        f: { plan: '출점 플랜', tier: '월 매출', dev: '주문 경로', sysfee: '시스템이용료 %', pay: '라쿠텐페이 이용료 %', points: '포인트 원자 %', aff: '어필리에이트 %(성과 발생 시만)', monthly: '월 고정비(출점료 + R-Messe)' },
        o: { g: '간바레! 플랜 (월 25,000엔)', s: '스탠다드 플랜 (월 65,000엔)', m: '메가샵 플랜 (월 130,000엔)', t0: '~50만엔', t1: '50만~100만엔', t2: '100만~500만엔', t3: '500만~1,000만엔', t4: '1,000만엔~', mobile: '모바일', pc: 'PC' },
        fee: { sysfee: '시스템이용료', pay: '라쿠텐페이 이용료', points: '포인트 원자', safety: '안전성·편의성 시스템이용료 (0.1%)', aff: '어필리에이트 수수료', monthly: '월 고정비 (배분)' },
        notes: ['시스템이용료는 월 매출 구간과 PC/모바일에 따라 변동: 간바레! 3.5~7.0%, 스탠다드/메가샵 2.0~4.5%(세별). 구간 경계는 참고치.', '라쿠텐페이 이용료는 월 결제액·평균 단가에 따라 2.5~3.5%.', '포인트 원자는 통상 1.0%. 쇼핑마라톤 등 이벤트 시 추가.', '월 출점료: 간바레! 25,000엔 / 스탠다드 65,000엔 / 메가샵 130,000엔, R-Messe 3,000~5,000엔(세별). 초기 등록비 60,000엔은 미포함.'],
        faq: [{ q: '라쿠텐 이치바 월 출점료는 얼마인가요?', a: '간바레! 플랜 25,000엔, 스탠다드 65,000엔, 메가샵 130,000엔(세별, 연 또는 반기 일괄 납부). 여기에 초기 등록비 60,000엔과 R-Messe 이용료 월 3,000~5,000엔이 추가됩니다.' }, { q: '시스템이용료는 어떻게 정해지나요?', a: '월 매출 구간과 PC/모바일 주문 경로로 정해집니다. 간바레!: PC 3.5~6.5%, 모바일 4.0~7.0%; 스탠다드/메가샵: PC 2.0~4.0%, 모바일 2.5~4.5%. 매출이 늘수록 요율이 내려갑니다.' }, { q: '그 외 매출 연동 비용은?', a: '라쿠텐페이 2.5~3.5%, 포인트 원자 1.0%~, 안전성·편의성 시스템이용료 0.1%, 어필리에이트 경유 매출에 실질 2.6~5.2%. 광고비·물류비는 별도.' }, { q: '변동비는 총 얼마나 되나요?', a: '보통 매출의 8~15%. 고정비는 주문 수로 나눠 건당 환산하므로 월 주문이 적을수록 건당 부담이 커집니다.' }] }
    }
  });
})(typeof window !== 'undefined' ? window : global);
