(function (root) {
  var SF = root.SF, F = SF.F, n = SF.n;
  SF.add({
    id: 'tiktok-eu', currency: 'EUR', flag: '🇪🇺', platform: 'TikTok Shop', region: 'EU', countries: ['DE','FR','IT','ES'],
    slug: { en: 'tiktok-shop-fee-calculator', de: 'tiktok-shop-gebuehren-rechner', fr: 'tiktok-shop-calculateur-commission', it: 'tiktok-shop-calcolo-commissioni', es: 'tiktok-shop-calculadora-comisiones', nl: 'tiktok-shop-commissie-berekenen', ja: 'tiktok-shop-fee-calculator', ko: 'tiktok-shop-fee-calculator' },
    fields: [F.price(24.99), F.shipping(3.99), F.cost(9), F.shipCost(3.5), F.cat(['9', '7', '4'], '9'), F.commission(9),
      { k: 'aff', l: 'aff', t: 'num', u: '%', d: 0, step: 0.5 }, F.other(), F.target()],
    fees: function (v) {
      var gross = n(v.price) + n(v.shipping);
      return [{ k: 'commission', a: gross * n(v.commission) / 100 }, { k: 'aff', a: n(v.price) * n(v.aff) / 100 }, { k: 'otherCost', a: gross * n(v.other) / 100 }];
    },
    sources: [{ n: 'Händlerbund: Gebührenerhöhung TikTok Shop 2026', u: 'https://ohn.haendlerbund.de/themen/marktplaetze/gebuehrenerhoehung-tiktok-shop-haendler-zahlen-2026-mehr' }, { n: 'TikTok Seller Center DE: Provisionsgebühr', u: 'https://seller-de.tiktok.com/university/essay?knowledge_id=4749658930186005' }, { n: 'E-commerce Nation: commissions TikTok Shop 5 % → 9 %', u: 'https://www.ecommerce-nation.fr/tiktok-shop-les-commissions-doublent-janvier-2026/' }, { n: 'Ecommerce Guru: TikTok Shop Italia, commissione al 9 %', u: 'https://www.ecommerceguru.it/tiktok-shop-italia-commissione-9-2026/' }],
    s: {
      en: { title: 'TikTok Shop Fee Calculator 2026 – EU Commission & Payout', desc: 'Free TikTok Shop seller fee calculator for Germany, France, Italy and Spain: 9 % commission, 4 % new-seller rate, creator fees, payout and profit.', h1: 'TikTok Shop Fee Calculator (EU, 2026)', intro: 'Since 8 January 2026 TikTok Shop charges 9 % commission (VAT included) on the order value including shipping in Germany, France, Italy, Spain and Ireland – 7 % for electronics and appliances, 4 % for new sellers during their first 60 days. Enter your price, costs and creator commission to see fees, payout and net profit per order.',
        cats: ['Standard (fashion, home, beauty, food …) – 9 %', 'Electronics, appliances, computers, phones, beauty devices – 7 %', 'New seller (first 60 days) – 4 %'], f: { aff: 'Creator (affiliate) commission %' }, fee: { commission: 'TikTok commission', aff: 'Creator commission' },
        notes: ['Commission is charged on the total order amount (item price + shipping paid by the customer), minus refunds.', 'Rates include VAT – no further tax is added on the fee.', 'You set the creator (affiliate) commission per product (typically 5–20 %); it only applies to sales made through creator content.', 'No subscription and no listing fees.'],
        faq: [{ q: 'What is the TikTok Shop commission in 2026?', a: '9 % since 8 January 2026 (previously 5 %), VAT included, on the order value. Electronics, appliances, computers, phones and beauty devices pay 7 %. New sellers pay 4 % for their first 60 days if they list at least five products within 15 days.' }, { q: 'Is commission charged on shipping?', a: 'Yes. The base is the total amount paid by the customer including shipping, minus refunds.' }, { q: 'What about creator commission?', a: 'You set it yourself per product, usually 5–20 %. It is only due when the sale comes through a creator. Enter it in the creator commission field.' }, { q: 'Is VAT added on top of the fee?', a: 'No. The 9 % and 7 % rates already include all applicable taxes.' }] },
      de: { title: 'TikTok Shop Gebührenrechner 2026 – Provision & Gewinn', desc: 'Kostenloser TikTok Shop Gebührenrechner für Deutschland: 9 % Provision, 4 % für neue Händler, Creator-Provision, Auszahlung und Nettogewinn.', h1: 'TikTok Shop Gebühren Rechner (Deutschland/EU, 2026)', intro: 'Seit dem 8. Januar 2026 berechnet TikTok Shop in Deutschland, Frankreich, Italien, Spanien und Irland 9 % Provision auf den Bestellwert inklusive Versandkosten – 7 % für Elektronik und Haushaltsgeräte, 4 % für neue Händler in den ersten 60 Tagen. Der Rechner zeigt Provision, Creator-Vergütung, Auszahlung und Nettogewinn pro Bestellung.',
        cats: ['Standard (Mode, Home, Beauty, Lebensmittel …) – 9 %', 'Elektronik, Haushaltsgeräte, Computer, Handys, Beauty-Geräte – 7 %', 'Neuer Händler (erste 60 Tage) – 4 %'], f: { aff: 'Creator-Provision (Affiliate) %' }, fee: { commission: 'TikTok-Provision', aff: 'Creator-Provision' },
        notes: ['Provision auf den Gesamtbetrag der Bestellung (Artikelpreis + vom Kunden gezahlter Versand), abzüglich Erstattungen.', 'Die Sätze verstehen sich inkl. MwSt. – keine weitere Steuer auf die Gebühr.', 'Creator-Provision legst du selbst pro Produkt fest (üblich 5–20 %); sie fällt nur bei Verkäufen über Creator-Content an.', 'Keine Grundgebühr, keine Einstellgebühr.'],
        faq: [{ q: 'Wie hoch ist die TikTok-Shop-Provision 2026?', a: 'Seit dem 8. Januar 2026 beträgt sie 9 % (vorher 5 %) inkl. MwSt. auf den Bestellwert. Für Elektronik, Haushaltsgeräte, Computer, Handys und Beauty-Geräte gelten 7 %. Neue Händler zahlen in den ersten 60 Tagen 4 %, wenn sie innerhalb von 15 Tagen mindestens fünf Produkte einstellen.' }, { q: 'Wird die Provision auch auf Versandkosten berechnet?', a: 'Ja. Grundlage ist der Gesamtbetrag der Bestellung inklusive der vom Kunden gezahlten Versandkosten, abzüglich Erstattungen.' }, { q: 'Was ist mit der Creator-Provision?', a: 'Die Affiliate-Provision für Creator legst du pro Produkt selbst fest, üblich sind 5–20 %. Sie fällt nur an, wenn der Verkauf über einen Creator zustande kommt. Trage sie im Feld „Creator-Provision“ ein.' }, { q: 'Kommt noch Mehrwertsteuer auf die Gebühr?', a: 'Nein. Die 9 % bzw. 7 % verstehen sich laut TikTok inklusive aller anfallenden Steuern.' }] },
      fr: { title: 'Calculateur de frais TikTok Shop 2026 – France et UE', desc: 'Calculateur gratuit des frais TikTok Shop : commission 9 %, 4 % pour les nouveaux vendeurs, commission créateur, montant reversé et bénéfice net.', h1: 'Calculateur de commission TikTok Shop (France/UE, 2026)', intro: 'Depuis le 8 janvier 2026, TikTok Shop prélève en France, Allemagne, Italie, Espagne et Irlande 9 % de commission (TVA incluse) sur le montant de la commande, frais de port compris – 7 % pour l’électronique et l’électroménager, 4 % pour les nouveaux vendeurs pendant 60 jours. Entrez votre prix, vos coûts et la commission créateur : le calculateur affiche frais, montant reversé et bénéfice net.',
        cats: ['Standard (mode, maison, beauté, alimentaire…) – 9 %', 'Électronique, électroménager, informatique, téléphonie, appareils beauté – 7 %', 'Nouveau vendeur (60 premiers jours) – 4 %'], f: { aff: 'Commission créateur (affiliation) %' }, fee: { commission: 'Commission TikTok', aff: 'Commission créateur' },
        notes: ['La commission s’applique au montant total de la commande (prix + frais de port payés par le client), après remboursements.', 'Les taux sont TVA incluse : aucune taxe supplémentaire sur la commission.', 'La commission créateur est fixée par vous, produit par produit (souvent 5–20 %) et ne s’applique qu’aux ventes via un créateur.', 'Pas d’abonnement ni de frais de mise en ligne.'],
        faq: [{ q: 'Quel est le taux de commission TikTok Shop en 2026 ?', a: '9 % depuis le 8 janvier 2026 (5 % auparavant), TVA incluse, sur le montant de la commande. 7 % pour l’électronique, l’électroménager, l’informatique, la téléphonie et les appareils de beauté. 4 % pour les nouveaux vendeurs pendant 60 jours, à condition de publier au moins cinq produits en 15 jours.' }, { q: 'La commission s’applique-t-elle aux frais de port ?', a: 'Oui. La base est le montant total payé par le client, frais de port compris, après déduction des remboursements.' }, { q: 'Et la commission créateur ?', a: 'Vous la fixez vous-même produit par produit (souvent 5–20 %). Elle n’est due que si la vente passe par un créateur. Saisissez-la dans le champ dédié.' }, { q: 'Y a-t-il de la TVA en plus sur la commission ?', a: 'Non, les taux de 9 % et 7 % s’entendent taxes comprises.' }] },
      it: { title: 'Calcolatore commissioni TikTok Shop 2026 – Italia e UE', desc: 'Calcolatore gratuito delle commissioni TikTok Shop: 9 %, 4 % per i nuovi venditori, commissione creator, importo accreditato e profitto netto.', h1: 'Calcolatore commissioni TikTok Shop (Italia/UE, 2026)', intro: 'Dall’8 gennaio 2026 TikTok Shop applica in Italia, Germania, Francia, Spagna e Irlanda una commissione del 9 % (IVA inclusa) sul valore dell’ordine, spedizione compresa: 7 % per elettronica ed elettrodomestici, 4 % per i nuovi venditori nei primi 60 giorni. Inserisci prezzo, costi e commissione creator: vedi subito commissioni, accredito e profitto netto.',
        cats: ['Standard (moda, casa, beauty, alimentari…) – 9 %', 'Elettronica, elettrodomestici, informatica, telefonia, dispositivi beauty – 7 %', 'Nuovo venditore (primi 60 giorni) – 4 %'], f: { aff: 'Commissione creator (affiliazione) %' }, fee: { commission: 'Commissione TikTok', aff: 'Commissione creator' },
        notes: ['La commissione si calcola sul totale dell’ordine (prezzo + spedizione pagata dal cliente), al netto dei rimborsi.', 'Le aliquote sono IVA inclusa: nessuna imposta aggiuntiva sulla commissione.', 'La commissione creator la decidi tu per ogni prodotto (di solito 5–20 %) e vale solo per le vendite generate dai creator.', 'Nessun canone mensile né costi di inserimento.'],
        faq: [{ q: 'Quanto è la commissione TikTok Shop nel 2026?', a: '9 % dall’8 gennaio 2026 (prima 5 %), IVA inclusa, sul valore dell’ordine. 7 % per elettronica, elettrodomestici, informatica, telefonia e dispositivi beauty. 4 % per i nuovi venditori nei primi 60 giorni, caricando almeno cinque prodotti entro 15 giorni.' }, { q: 'La commissione si applica anche alla spedizione?', a: 'Sì. La base è l’importo totale pagato dal cliente, spedizione inclusa, al netto dei rimborsi.' }, { q: 'E la commissione creator?', a: 'La imposti tu per ogni prodotto (di solito 5–20 %). Si paga solo se la vendita arriva tramite un creator. Inseriscila nel campo dedicato.' }, { q: 'C’è IVA in più sulla commissione?', a: 'No, le aliquote del 9 % e del 7 % sono già comprensive di imposte.' }] },
      es: { title: 'Calculadora de comisiones TikTok Shop 2026 – España y UE', desc: 'Calculadora gratuita de comisiones de TikTok Shop: 9 %, 4 % para vendedores nuevos, comisión de creador, importe recibido y beneficio neto.', h1: 'Calculadora de comisiones TikTok Shop (España/UE, 2026)', intro: 'Desde el 8 de enero de 2026 TikTok Shop cobra en España, Alemania, Francia, Italia e Irlanda una comisión del 9 % (IVA incluido) sobre el valor del pedido, envío incluido: 7 % en electrónica y electrodomésticos y 4 % para nuevos vendedores durante sus primeros 60 días. Introduce precio, costes y comisión de creador para ver tarifas, importe recibido y beneficio neto por pedido.',
        cats: ['Estándar (moda, hogar, belleza, alimentación…) – 9 %', 'Electrónica, electrodomésticos, informática, telefonía, aparatos de belleza – 7 %', 'Nuevo vendedor (primeros 60 días) – 4 %'], f: { aff: 'Comisión de creador (afiliación) %' }, fee: { commission: 'Comisión TikTok', aff: 'Comisión de creador' },
        notes: ['La comisión se aplica al importe total del pedido (precio + envío pagado por el cliente), descontando reembolsos.', 'Las tarifas incluyen IVA: no se añade ningún impuesto sobre la comisión.', 'La comisión de creador la fijas tú por producto (normalmente 5–20 %) y solo se aplica a ventas generadas por creadores.', 'Sin cuota mensual ni coste por publicar.'],
        faq: [{ q: '¿Cuál es la comisión de TikTok Shop en 2026?', a: '9 % desde el 8 de enero de 2026 (antes 5 %), IVA incluido, sobre el valor del pedido. 7 % en electrónica, electrodomésticos, informática, telefonía y aparatos de belleza. 4 % para nuevos vendedores durante 60 días si publican al menos cinco productos en 15 días.' }, { q: '¿Se aplica la comisión al envío?', a: 'Sí. La base es el importe total pagado por el cliente, envío incluido, menos los reembolsos.' }, { q: '¿Y la comisión de creador?', a: 'La fijas tú por producto (normalmente 5–20 %) y solo se paga cuando la venta llega a través de un creador. Introdúcela en el campo correspondiente.' }, { q: '¿Hay IVA adicional sobre la comisión?', a: 'No. Las tarifas del 9 % y 7 % ya incluyen impuestos.' }] },
      nl: { title: 'TikTok Shop commissie berekenen 2026 – kosten en winst', desc: 'Gratis TikTok Shop commissiecalculator: 9 % commissie, 4 % voor nieuwe verkopers, creatorcommissie, uitbetaling en nettowinst per product.', h1: 'TikTok Shop commissie berekenen (EU, 2026)', intro: 'Sinds 8 januari 2026 rekent TikTok Shop in Duitsland, Frankrijk, Italië, Spanje en Ierland 9 % commissie (incl. btw) over de orderwaarde inclusief verzendkosten – 7 % voor elektronica en huishoudelijke apparaten, 4 % voor nieuwe verkopers in de eerste 60 dagen. Vul prijs, kosten en creatorcommissie in en zie direct kosten, uitbetaling en nettowinst per bestelling.',
        cats: ['Standaard (mode, wonen, beauty, food …) – 9 %', 'Elektronica, huishoudelijke apparaten, computers, telefoons, beautyapparaten – 7 %', 'Nieuwe verkoper (eerste 60 dagen) – 4 %'], f: { aff: 'Creatorcommissie (affiliate) %' }, fee: { commission: 'TikTok-commissie', aff: 'Creatorcommissie' },
        notes: ['De commissie wordt berekend over het totale orderbedrag (prijs + door de klant betaalde verzendkosten), na terugbetalingen.', 'De tarieven zijn inclusief btw: er komt geen extra belasting over de commissie.', 'De creatorcommissie bepaal je zelf per product (meestal 5–20 %) en geldt alleen voor verkopen via creators.', 'Geen abonnement en geen plaatsingskosten.'],
        faq: [{ q: 'Hoe hoog is de TikTok Shop-commissie in 2026?', a: '9 % sinds 8 januari 2026 (eerder 5 %), inclusief btw, over de orderwaarde. Elektronica, huishoudelijke apparaten, computers, telefoons en beautyapparaten betalen 7 %. Nieuwe verkopers betalen 4 % in de eerste 60 dagen als ze binnen 15 dagen minstens vijf producten plaatsen.' }, { q: 'Wordt er commissie over verzendkosten gerekend?', a: 'Ja. De basis is het totale bedrag dat de klant betaalt, inclusief verzendkosten, min terugbetalingen.' }, { q: 'Hoe zit het met de creatorcommissie?', a: 'Die stel je zelf in per product, meestal 5–20 %. Je betaalt hem alleen als de verkoop via een creator loopt. Vul hem in bij het veld creatorcommissie.' }, { q: 'Komt er nog btw bovenop de commissie?', a: 'Nee. De tarieven van 9 % en 7 % zijn al inclusief alle belastingen.' }] },
      ja: { title: 'TikTok Shop（EU）手数料計算ツール 2026｜手数料・入金額・利益', desc: 'ドイツ・フランス・イタリア・スペイン・アイルランドのTikTok Shop手数料（9%、家電7%、新規4%）とクリエイター報酬を入力し、入金額・純利益・損益分岐価格を無料計算。', h1: 'TikTok Shop 手数料計算ツール（EU、2026年版）', intro: '2026年1月8日以降、TikTok ShopはEU（ドイツ・フランス・イタリア・スペイン・アイルランド）で注文金額（送料込み）に対し9%（税込）の手数料を課しています。家電・電子機器は7%、新規出品者は最初の60日間4%。価格・原価・クリエイター報酬を入力すると、手数料・入金額・純利益が表示されます。',
        cats: ['標準（ファッション・ホーム・美容・食品など）– 9%', '家電・電子機器・PC・スマホ・美容機器 – 7%', '新規出品者（最初の60日間）– 4%'], f: { aff: 'クリエイター報酬（アフィリエイト）%' }, fee: { commission: 'TikTok手数料', aff: 'クリエイター報酬' },
        notes: ['手数料は注文合計額（商品価格＋購入者が支払う送料）から返金分を差し引いた金額にかかります。', '料率は税込表示のため、手数料に追加の税はかかりません。', 'クリエイター報酬は商品ごとに出品者が設定（通常5〜20%）し、クリエイター経由の販売にのみ発生します。', '月額費用・出品料はありません。'],
        faq: [{ q: '2026年のTikTok Shop手数料は？', a: '2026年1月8日から9%（以前は5%）、税込、注文金額に対して。家電・電子機器・PC・スマホ・美容機器は7%。新規出品者は15日以内に5商品以上出品すると最初の60日間4%。' }, { q: '送料にも手数料がかかりますか？', a: 'はい。購入者が支払った合計額（送料込み）から返金分を引いた金額が対象です。' }, { q: 'クリエイター報酬とは？', a: '商品ごとに自分で設定する報酬（通常5〜20%）で、クリエイター経由で売れた場合のみ発生します。該当の欄に入力してください。' }, { q: '手数料に税は上乗せされますか？', a: 'いいえ。9%・7%はすでに税込の料率です。' }] },
      ko: { title: 'TikTok Shop (EU) 수수료 계산기 2026 | 커미션·정산금·순이익', desc: '독일·프랑스·이탈리아·스페인·아일랜드 TikTok Shop 수수료(9%, 전자제품 7%, 신규 셀러 4%)와 크리에이터 커미션을 반영해 정산금·순이익·손익분기 판매가를 무료 계산.', h1: 'TikTok Shop 수수료 계산기 (EU, 2026년)', intro: '2026년 1월 8일부터 TikTok Shop은 EU(독일·프랑스·이탈리아·스페인·아일랜드)에서 주문금액(배송비 포함)의 9%(부가세 포함)를 수수료로 부과합니다. 전자제품·가전은 7%, 신규 셀러는 첫 60일간 4%. 판매가·원가·크리에이터 커미션을 입력하면 수수료·정산금·순이익이 바로 계산됩니다.',
        cats: ['일반 (패션·홈·뷰티·식품 등) – 9%', '전자제품·가전·컴퓨터·휴대폰·미용기기 – 7%', '신규 셀러 (첫 60일) – 4%'], f: { aff: '크리에이터 커미션(제휴) %' }, fee: { commission: 'TikTok 수수료', aff: '크리에이터 커미션' },
        notes: ['수수료는 주문 총액(상품가 + 구매자 부담 배송비)에서 환불액을 뺀 금액에 부과됩니다.', '요율은 부가세 포함이라 수수료에 세금이 추가되지 않습니다.', '크리에이터 커미션은 상품별로 셀러가 정하며(보통 5~20%), 크리에이터 콘텐츠를 통한 판매에만 발생합니다.', '월 이용료·등록비 없음.'],
        faq: [{ q: '2026년 TikTok Shop 수수료는 얼마인가요?', a: '2026년 1월 8일부터 9%(이전 5%), 부가세 포함, 주문금액 기준. 전자제품·가전·컴퓨터·휴대폰·미용기기는 7%. 신규 셀러는 15일 안에 5개 이상 상품을 등록하면 첫 60일간 4%.' }, { q: '배송비에도 수수료가 붙나요?', a: '네. 구매자가 결제한 총액(배송비 포함)에서 환불을 뺀 금액이 기준입니다.' }, { q: '크리에이터 커미션은 뭔가요?', a: '상품별로 직접 정하는 제휴 수수료(보통 5~20%)로, 크리에이터를 통해 팔린 경우에만 지급합니다. 해당 칸에 입력하세요.' }, { q: '수수료에 부가세가 추가되나요?', a: '아니요. 9%·7% 요율은 이미 세금 포함입니다.' }] }
    }
  });
})(typeof window !== 'undefined' ? window : global);
